### ISSUE TITLE
Увеличение размера диска из консоли АТС приводит к потере данных

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#101]
2021.2.169-dev

АТС развернута в Яндекс облаке. Увеличиваем размер дополнительного диска для виртуальной машины в яндекс облаке. После перезагрузки выполняем действия в консоли [6] Data Storage - [3] Increase the data storage partition with an unallocated area
Через некоторое время переподключаемся по ssh, видим сообщение "Диск не подключен". Выполняем действия [6] Data storage - [1] Mount drive as data storage
После завершения процедуры, диск смонтирован, данных на диске нет.

**Comment by boffart** [comment]
Надеюсь бекап данных был сделан. 
Проверим, спасибо за обратную связь.

**Comment by boffart** [comment]
Исправлено.
