### ISSUE TITLE
При использовании правила, дописывающего цифру, в истории звонков отображается только эта цифра

### ISSUE THREAD

**Issue by IamMushroom** [mikopbx/Core#105]
1. Создал в исходящих маршрутах правило, отсекающее у 11-значных номеров 8, и дописывающее 7.
2. Поднял правило на 1 место.
3. В истории звонков во всех вызовах в "Кому" записана только цифра 7.
4. Передвинул правило на 2 место, и потом опять на первое.
5. Проблема решилась.

![image](https://user-images.githubusercontent.com/12426736/121358234-1d7e4500-c93b-11eb-99a1-a4d536da9413.png)

**Comment by IamMushroom** [comment]
Да, забыл. Версия MIKOPBX ver: 2021.1.54

**Comment by boffart** [comment]
Проблема известная. Решена в https://github.com/mikopbx/Core/releases/tag/2021.2.169-dev
Скоро выпустим релиз.
