### ISSUE TITLE
Не меняется параметр defaultlanguage в asterisk.conf при смене языка в web интерфейсе

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#116]
MikoPBX 2021.2.194

Не меняется параметр defaultlanguage в asterisk.conf при смене языка в web интерфейсе.
Требуется перезагрузка АТС, для изменения этого параметра.

**Comment by boffart** [comment]
Основная беда - при смене параметра необходим рестарт службы asterisk 
Соответственно - будут сброшены все вызовы.

**Comment by boffart** [comment]
Поправил
