### ISSUE TITLE
Добавить звуковые файлы для Украины

### ISSUE THREAD

**Issue by boffart** [mikopbx/Core#117]
https://github.com/vikdon/asterisk-core-sounds-uk

**Comment by boffart** [comment]
Обсуждение на эту. тему 
https://local.com.ua/forum/topic/71253-asterisk-українські-системні-голосові-файли/

**Comment by jorikfon** [comment]
Я попросил Сидорова связаться с ними узнать какая лицензия, можно ли нам это добавить в репозиторий...

**Comment by boffart** [comment]
I think this is not relevant yet.
