### ISSUE TITLE
Для правил входящих маршрутов добавить вариант воспроизвести звуковой файл

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#123]
![2021-07-16 17 37 28](https://user-images.githubusercontent.com/5922918/125964855-470eeefc-8f7a-40e9-a4a6-250198c736ca.jpg)

**Comment by Realmagnum** [comment]
Я перевожу вызов на отдельную ИВР с проигрыванием нужного сообщения и Hangup в конце.

**Comment by boffart** [comment]
Мб удалить задачу? Решается через IVR и норм.

**Comment by Realmagnum** [comment]
Думаю да.

**Comment by jorikfon** [comment]
> Мб удалить задачу? Решается через IVR и норм.

Ну это костыль же. Почему нормально не сделать? :)

**Comment by Realmagnum** [comment]
К тому же с доп.ИВР в логах труднее дебажить.

**Comment by boffart** [comment]
Готово
