### ISSUE TITLE
Не срабатывает перевод на конференцию 1111 в рабочей

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#124]
1. Не получилось позвонить и понабрать из IVR
2. Не получилось перевести через ## на 1111

Может это проблема диалплана, а может модуля умной маршрутизации, пока не понятно. Если к модулю относится, то надо перенести в тот проект.

**Comment by boffart** [comment]
Оно так никогда не работало. 
Переадресация возможна только "слепая". 
В конференцию намеренно ограничен вход "только НЕ Local каналы", это связано с особенностями легирования истории звонков. Из за Local каналов получалась каша. 

Я поправил, через IVR теперь можно попасть в конференцию. 
Если нужно переадресовать собеседника в конференцию - следует использовать "**слепую**" переадресацию.
