### ISSUE TITLE
Голосовая почта и оповещения на телефоны

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#126]
Утром звонила Наташка, все телефоны светятся красным. Долго разбирался, оказалось это сообщение на голосовую почту. 
Клиенты тоже писали жаловались, что трудно удалить, надо обязательно звонить на спец номер и чистить эту почту.

Можем ли мы делать автоматом сообщение прочитанным после отправки его на email и выключать опопвещение на устройства, о том что такая голосовая почта есть?

Еще бы хорошо включить записть стандартную CDR если это возможно для такого звонка, чтобы можно было ее прослушать из журнала звонков в 1С по стандартной схеме.
Плюс народ просит удалять саму запись Voicemail, наверное было бы идеально если бы она была в CDR, а оригинальную удалить, т.к. она там лежит навсегда, даже после прослушивания как я понял.

**Comment by boffart** [comment]
Готово
