### ISSUE TITLE
Добавить отображение всех подключенных ендпоинтов в сотруднике по двойному Ctrl

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#127]

**Comment by boffart** [comment]
Поправил.

**Comment by sazhyk** [comment]
Браузер Google Chrome, MIKOPBX ver: 2021.3.86.
После двойного CTRL слетает верстка страницы. Нет вертикального скролла. Необходимо перезагрузить страницу, чтобы это исправить.

**Comment by boffart** [comment]
Проверил в Версия 96.0.4664.93 (Официальная сборка), (x86_64) 
На актуальной сборке АТС проблемы не обнаружил. 
В Safari тоже все ок. 

Попробуйте почистить кэш в браузере.
