### ISSUE TITLE
На странице регистрации добавить проверку наличия интернета на станции

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#147]
Если интернета нет, то вместо формы регистрации показывать сообщение вместо формы регистрации.

**Comment by boffart** [comment]
вуб очередь, нет смысла форму показывать пока интерента нет. Можно прятать стораницу управления лицензией и показывать статическую страницу с слюзением о том что надо сделать. Чаще всего с DNS проблемы или Gateway

**Comment by jorikfon** [comment]
проверить может из ядра curl "https://lic.miko.ru/protect/v1/ping"
