### ISSUE TITLE
Настройка сети через php

### ISSUE THREAD

**Issue by alglyzin** [mikopbx/Core#15]
Добрый день. Я автоматизирую установку MikoPBX на чистый виртуальный сервер. Написал скрипт на php, который запускаю после установки. Скрипт настраивает сеть АТС необходимым образом. В 72 версии все работает, а в 124 уже нет. В чем проблема?

```
	$network = new Network();
	$system  = new System();

	$data = array();
	$data['subnet'] = 24;
	$data['primarydns'] = '8.8.8.8';
	
	if(isset($options['ipaddr']) || isset($options['i'])) {
		$data['ipaddr'] = isset($options['ipaddr']) ? $options['ipaddr'] : $options['i'];
	}
	
	if(isset($options['gateway']) || isset($options['g'])) {
		$data['gateway'] = isset($options['gateway']) ? $options['gateway'] : $options['g'];
	}	
	
	$network->update_net_settings($data);
	$network->resolvconf_generate();
	$network->lan_configure();
	$system->nginx_start();
```

**Comment by boffart** [comment]
А ошибки какие либо сыпет? 
В 2020.2.XXX версии  ядро АТС значительно изменилось. Этот скрипт там не будет работать.

**Comment by alglyzin** [comment]
Помогите видоизменить скрипт. Одному Вам известно что изменилось.

**Comment by boffart** [comment]
У вас переменная $options не инициализирована. Мб. в этом беда? 

Вот пример скрипта настройки сети:
https://github.com/mikopbx/Core/blob/master/etc/rc/networking
`    $network = new Network();
    $network->resolvconf_generate();
    $network->lo_configure();
    $network->lan_configure();`

Вот еще один пример:
https://github.com/mikopbx/Core/blob/a5f6c79746f246deaa42e44e9f61e055c449ddbf/etc/rc/console_menu#L143

`$data = [];
            $data['ipaddr']  	= $lanip;
            $data['subnet']  	= $lanbits;
            $data['gateway'] 	= $gwip;
            $data['primarydns'] = $dnsip;
            $data['dhcp']       = '0';

            echo Util::translate('The LAN interface will now be configured ...');
            $network->update_net_settings($data);
            $network->resolvconf_generate();
            $network->lan_configure();
            $system->nginx_start();`
