### ISSUE TITLE
Не срабатывает нерабочее время и голосовой файл в ivr

### ISSUE THREAD

**Issue by timracer** [mikopbx/Core#168]
Здравствуйте!
Установлен последний релиз. Не срабатывает нерабочее время и голосовое приветствие в ivr.Часовой пояс выставлен верный, время синхронизируется автоматически

**Comment by boffart** [comment]
Приложите для такого звонка логи **asterisk/verbose**  из раздела "**Системные логи**". 
Приложите скриншоты как настроено "Нерабочее время".
