### ISSUE TITLE
Записи в системном файле появляются после перезагрузки

### ISSUE THREAD

**Issue by atar90** [mikopbx/Core#171]
При внесении изменений через веб-интерфейс АТС (Система -> Кастомизация системных файлов)  в системный файл **/etc/static-routes** в режиме "**Заменять полностью**" изменения в файле не появляются после нажатия кнопки "Сохранить". Изменения вносятся в файл после перезагрузки АТС.

**Comment by boffart** [comment]
Это нормально. 
Благо эти настройки как правило вносятся однократно.

**Comment by jorikfon** [comment]
А че нормально, сетвевые настройки сразу применяются, IP адрес, DNS, Шлюз, VLAN, а это только после ребута. В любом случае, если нормально то на странице WIKI допиши, требует ребута. 
Но тогда может по всем сетевым так сделать нам?

**Comment by boffart** [comment]
Реализовал автоматическое применение изменений файла "**/etc/static-routes**". При кастомизации файла через web интерфейс правила будут применяться сразу. Перезагрузка не требуется. 

Я всегда опасаюсь, что при ручной настройке сети пользователь сломает маршрутизацию и не сможет зайти на машину. Пока не ясно как с минимальными затратами реализовать проверки вводимых команд.
