### ISSUE TITLE
Добавить в обновление АТС исправление доступа к папке "custom modules" на storage.

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#173]
Пока не сделали вручную chmod 777 -R не работали AGI скрипты первой панели

**Comment by jorikfon** [comment]
Странная фигня, у PHP-AGI скрипта есть права на исполнение, но он не исполняется, Asterisk пишет Permission denied. Установка, переустановка модуля, назначение прав на файл ни как не помогало, а вот когда на корневую папку с модулями сделали 777, заработало.

**Comment by boffart** [comment]
Готово
