### ISSUE TITLE
Нет возможности отключить qualify

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#184]
MikoPBX 2021.3.86

В дополнительных параметрах провайдера/сотрудника указываем qualify_frequency = 0, в конфиге устанавливается значение 60. Баг или фича? Документация asterisk позволяет устанавливать 0 для отключения qualify

```
[aor]
qualify_frequency = 0
```

**Comment by boffart** [comment]
видимо так отрабатывает проверка на пустое значение
empty(0) === true

гляну

**Comment by boffart** [comment]
Поправил.
