### ISSUE TITLE
Завершение вызова при попытке безусловного перевода звонка, забранного из очереди

### ISSUE THREAD

**Issue by atar90** [mikopbx/Core#191]
**Шаги воспроизведения:**
1. Внешний входящий звонок попадает на очередь.
2. Его принимает внутренний номер.
3. Делает безусловный перевод (**), у звонящего звонок обрывается.

В моем логе : 
внешний звонок с 74993809034.
попал на очередь 2001, 
принял внутренний 201, 
внутренний 202 позвонил на конференцию 222 (просто чтобы там кто-то был)
201 переводит абонента 74993809034 на конференцию 222
Отбой 74993809034
Потом 202 вышел из конференции
[obriv_zvonka_iz_ocheredi.txt](https://github.com/mikopbx/Core/files/7286122/obriv_zvonka_iz_ocheredi.txt)

**Comment by boffart** [comment]
Поправил.

**Comment by boffart** [comment]
либо вручную внести правки
https://github.com/mikopbx/Core/commit/73a7f3e1d7eb02b4974142caa10c20ba88b0646a?branch=73a7f3e1d7eb02b4974142caa10c20ba88b0646a&diff=unified

либо скачать новую сборку из тимсити (в течении часа точно соберется).
