### ISSUE TITLE
Fix CA certs update on TeamCity build step

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#192]
Устарели

**Comment by boffart** [comment]
судя по всему сейчас это не актуально.

**Comment by jorikfon** [comment]
Проблема актуальная, из-за устаревших сертификатов не проходит проверка связи с сервером лицензирования, и перестали качаться модули в DEV версии.
`"messages": [
        "cURL error 60: SSL certificate problem: certificate is not yet valid (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://files.miko.ru/s/busOYHAdlneWfrH/downloadCurl return code -1. "
    ],`

Вижу что в Симсити есть шаг в сборщике, но он вероятно не работает, проблему видно на 72 станции.

**Comment by boffart** [comment]
Добавил шаг обновления CA сертификатов при инкрементальной сборке .
Сейчас не 72 станции нет проблем с доступом ресурсам MIKO.
