### ISSUE TITLE
Отправка голосовой почты.

### ISSUE THREAD

**Issue by alexinc-2000** [mikopbx/Core#199]
Поскольку по плану все голосовые сообщения остаются в CDR, все-таки нужно, чтобы voicemail отправлялся именно тому сотруднику, на внутренний номер которому позвонили. 
А то получается - позвонили сотруднику - у него стоит voicemail и все сообщения упали админу, или секретарю. А человек не получает никакого уведомления что был звонок.
Проверяется это следующим образом:
Настраиваем voicemail. 
У сотрудника настраиваем Маршрутизацию - при неответе или номер недоступен - Voicemail.
И теперь при звонке сотруднику и уходу на voicemail  сотрудник не будет знать, что ему звонили и о чем просили. Ему придется либо лезть в общий ящик и разбираться там либо запрашивать специально обученного человека.

**Comment by alexinc-2000** [comment]
Осмелюсь предложить решение как в форуме:
**1. В диалплане voicemail:**
1,Goto(voice_mail_peer,${CALLERID(dnid)},1)
**2. в existantions.conf:**
[voice_mail_peer]
exten => _X!,1,Answer()
same => n,ExecIf($["${CHANNEL:0:5}" == "Local"]?Set(pl=${IF($["${CHANNEL:-1}" == "1"]?2:1)}))
same => n,ExecIf($["${CHANNEL:0:5}" == "Local"]?Set(bridgePeer=${IMPORT(${CUT(CHANNEL,\;,1)}\;${pl},BRIDGEPEER)}))
same => n,ExecIf($[ "${FROM_CHAN}" == "${bridgePeer}" ]?ChannelRedirect(${bridgePeer},${CONTEXT},${EXTEN},2))
same => n,AGI(/usr/www/src/Core/Asterisk/agi-bin/clean_timeout.php)
same => n,Gosub(voicemail_start,${EXTEN},1)
same => n,VoiceMail(${EXTEN}@voicemailcontext)
same => n,Hangup()
exten => h,1,Gosub(voicemail_end,${EXTEN},1)
same => n,Hangup()
**3. В карточке сотрудника напротив почты поставить флажок - голосовая почта. Либо просто - наличие емайла подразумевает наличие голосовой почты.**
**4. Раскомментировать код в VoiceMailConf.php** (https://github.com/mikopbx/Core/blob/master/src/Core/Asterisk/Configs/VoiceMailConf.php#L80).
Ну собственно и все.
Возможно, я чего-то не учел.

**Comment by alexinc-2000** [comment]
Разобрался вроде. Нужно в заголовки добавить 
use MikoPBX\Common\Models\{Sip,Extensions,Users};

**Comment by boffart** [comment]
Все "**Сотрудники**", кто пропустил вызов, в случае, если клиент направлен на **voicemail** получат email с записью голосового сообщения. 
Конечно, только в случае, если email заполнен в карточке сотрудника и оповещения на email настроены.
