### ISSUE TITLE
Добавить пакет mc (Midnight Commander)

### ISSUE THREAD

**Issue by alexinc-2000** [mikopbx/Core#203]
Если есть возможность - добавить в сборку ядра mc (Midnight Commander). Разбираться с файлами будет удобнее. Вещь не критичная, но удобная для правки и обслуживания.
В пакетах t2sde присутствует

**Comment by boffart** [comment]
добавлял ее в dev сборку, но после удалил, 5Мб слишком жирно:
[SIZE] 5.01 MB, 161 files
да и смысла в нем нет, MikoPBX позиционирует как простую АТС, где не требуется знание Linux. 
если нужен файловый менеджер, то используйте **sftp**.
