### ISSUE TITLE
Проверить ушла ли ошибка конвертации таблицы call_events на DEV релизе MikoPBX

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#224]
В релизе при загрузке долго стоит на строчке конвертации структуры базы

![image_2021-11-09_10-04-55](https://user-images.githubusercontent.com/5922918/140899499-3f00c596-1976-4d0d-af50-af769be69766.png)

Для воспроизведения поставить релиз, залить туда events_log.db файл истории из папки **ATarClients/inbox/Задача по CDR** в папку **/storage/usbdisk1/mikopbx/astlogs/asterisk/**

Воспроизвести что действительно при загрузке станция спотыкается на этом.

Обновить до последнего DEV релиза, проверить что ошибка ушла.
Если не ушла, перевесить задачу на Алексея, если ушла то закрыть как выполненную.

**Comment by boffart** [comment]
Проверил у себя на актуальной версии develop. 
Все ок.

**Comment by jorikfon** [comment]
Ок, Миша удалил свой файл по ошибке, проверить не на чем, закрываю пока.
