### ISSUE TITLE
ISO образ не грузится с USB

### ISSUE THREAD

**Issue by tERB00** [mikopbx/Core#233]
Balena говорит что образ не является загрузочным, Rufus просто зависает при выборе образа, Imageusb записывает образ, но пк с него не грузится (ставлю на реальное железо).

**Comment by boffart** [comment]
См. другую задачу:
https://github.com/mikopbx/Core/issues/225

Образ из последнего релиза не является гибридным. 
Варианты:

- Установить предыдущую версию АТС и после обновить на актуальную 
- Установить АТС на флэшку, не в виде Live USB, используйте образ raw. 
- Используя консольное приложение linux isohybrid слелать образ гибридным

**Comment by tERB00** [comment]
В новом релизе образы по прежнему не рабочие. ISO не грузится, IMG не проходит верификацию записи а из RAW не возможно запустить установку на диск.
