### ISSUE TITLE
Не все записи конвертируются в MP3 (в рабочей)

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#241]
Какой бы я час не выбрал, в папке с записями всегда есть WAV фалы не сконвертированные в mp3
Например 
`~# ls /storage/usbdisk1/mikopbx/astspool/monitor/2021/12/23/13/mikopbx-1640255891.7912_Xy2Dt4

mikopbx-1640255891.7912_Xy2Dt4_in.wav   mikopbx-1640255891.7912_Xy2Dt4_out.wav  mikopbx-1640255891.7912_Xy2Dt4.wav`

И место выжрано на дисках, вероятно потому-то это не единичный баг

**Comment by boffart** [comment]
Доработал конвертацию.
