### ISSUE TITLE
VOICEMAIL no recordings longer than 10 seconds

### ISSUE THREAD

**Issue by atar90** [mikopbx/Core#246]
При звонке на VOICEMAIL записи разговоров длительностью больше 10 секунд (приблизительно) не прослушиваются в веб-интерфейсе АТС.
Меньше - прослушиваются.
На АТС не нашел папку
storage/usbdisk1/mikopbx/callrecordings

![файлы записей](https://user-images.githubusercontent.com/87700676/147750672-6fdec544-39d5-498f-8bdd-d6a2f6bd609d.png)
При прослушивании сообщений (звонок на *001) - ответ "**Нет новых сообщений**".

**Comment by boffart** [comment]
Как настроен маршрут звонка? Как ты проводишь тесты? 

How is the call route configured? How do you conduct tests?

**Comment by boffart** [comment]
`/storage/usbdisk1/mikopbx/callrecordings` - ??? 

Recordings of conversations are stored here:
`/storage/usbdisk1/mikopbx/astspool/monitor/`

**Comment by boffart** [comment]
Reproduced the problem. The voicemail file went to email, but it wasn't attached to the call history.
