### ISSUE TITLE
Weird Timezone + AutoProvision

### ISSUE THREAD

**Issue by emassen** [mikopbx/Core#247]
I'm really enjoying the updates. The Auto-Provisioning part I believe should have an option to put the MAC Address on the desired extension. Another point would be the timezone in Brazil I have to use -21 and correct for UTC it should be -3. Thank you very much.

**Comment by boffart** [comment]
_Another point would be the timezone in Brazil I have to use -21 and correct for UTC it should be -3._
**Done**

**Auto-Provisioning part**
I created a task:
https://github.com/mikopbx/ModuleAutoprovision/issues/8
