### ISSUE TITLE
Docker невозможно сохранить настройки

### ISSUE THREAD

**Issue by boffart** [mikopbx/Core#248]
https://qa.mikopbx.com/11701/новый-docker-2021-4-175-не-сохраняет-настройки

**Comment by boffart** [comment]
Интересная статья на тему прав доступа. 
https://jtreminio.com/blog/running-docker-containers-as-current-host-user/

Если docker контейнер использует несколько различных пользователей, которые пишут в подключенные к контейнеру каталоги, то начинаются проблемы с правами доступа.

**Comment by boffart** [comment]
Решение:
На хост системе добавить пользователя и группу с ID (имя может быть произвольным):
```
groupadd -g 1011 www-mikopbx 
useradd -l -u 1011 -g www-mikopbx www-mikopbx
```

**Comment by boffart** [comment]
Нельзя кастомизировать **REDIS_PORT**

**Comment by boffart** [comment]
Готово

**Comment by un7known** [comment]
> Нельзя кастомизировать **REDIS_PORT**

А как тогда можно запустить несколько контейнеров mikopbx?

**Comment by boffart** [comment]
с новым релизом это станет возможно. 
либо прокатить текущий контейнер - но мб это не совсем просто, все коммиты прикреплены к задаче.
