### ISSUE TITLE
Не проходят входящие звонки при длине did номера 1 символ

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#252]
MikoPBX 2021.4.175

В логах ошибка:
[2022-01-12 08:27:07] ERROR[27582][C-00000031] app_stack.c: Attempt to reach a non-existent destination for Gosub: (Context:add-trim-prefix-clid, Extension:2, Priority:1)

**Comment by boffart** [comment]
я бы это фичей назвал )) 
короткий DID не информативен. 
подумаю как обыграть

**Comment by ivstep** [comment]
Может тогда в веб интерфейсе добавить проверку на длину логина?

**Comment by boffart** [comment]
Поправил. работает теперь и логином (DID) из одного цифрового символа.

**Comment by boffart** [comment]
Добавил проверку на длину логина.
