### ISSUE TITLE
Можем ли мы ACPI пакет добавить для корректного управления машиной из виртуализации

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#255]
Вроде небольшой.
http://t2sde.org/packages/8.0/acpid

Пишут что может помочь корректной работе в Proxmox, машина будет корректно перегружаться по команде гипервизора, по CTRL+ALT+DEL

**Comment by boffart** [comment]
проект с 2009 годе не обновляется. 
сходу собрать не вышло

**Comment by boffart** [comment]
Настроил аналогично https://pve.proxmox.com/wiki/QEMU/KVM_ACPI_Guest_Shutdown

**Comment by boffart** [comment]
Готово, осталось дождаться сборки t2.
