### ISSUE TITLE
Можно ли добавить вариант любое количество цифр для исходящих правил?

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#257]
Хочу сделать правило звонков на телеграмм, например.
Набираем префикс 987, а дальше номер, который надо передать провайдеру с кодом страны.
Если в поле **любое количество цифр** убрать значение, хотелось бы чтобы станция принимала любое количество цифр и передавала провайдеру, чтобы не рисовать отдельно для каждой страны свой маршрут.
Для удобства я могу в интерфейсе при незаполненном поле отображать знак бесконечности или слово, **любое**.

**Comment by boffart** [comment]
ну так это уже давно сделано. [см. документацию](https://wiki.mikopbx.com/outbound-routes)
проверил, работает

**Comment by boffart** [comment]
В поле "**любое количество цифр**" допустимы варианты:
- пустое значение - неограниченное кол-во цифр после префикса
- значение "0" - только префикс
- значение > 0 - фиксированное количество цифр после префикса

**Comment by jorikfon** [comment]
Отлично. Тогда повешу на себя чтобы как-то в интерфейсе обыграть этот момент понятнее. Проверил работает, как надо.
