### ISSUE TITLE
При установке модуля с обновленной сттруктурой базы данных не происходит обновление

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#261]
В модуле CTI добавили колонку в таблицу. Ожидаю что при установке модуля произойдет обновление структуры данных.
Есть метод 
https://github.com/mikopbx/Core/blob/7ddf0df8c4fa0b3d0eae4da455457b4884a7faa1/src/Modules/Setup/PbxExtensionSetupBase.php#L438-L459

Не сработал.
<img width="1167" alt="Screenshot 2022-01-28 at 13 26 17" src="https://user-images.githubusercontent.com/5922918/151531426-ee1c059b-8062-4059-8013-03bd035a1718.png">

**Comment by boffart** [comment]
Я при разработке модулей вот такой конструкцией запускаю обновление структуры DB

```
$ud = new \MikoPBX\Core\System\Upgrade\UpdateDatabase();
$ud->createUpdateDbTableByAnnotations(\Modules\ModuleTelegramProvider\Models\ModuleTelegramProvider::class);
```
Соответственно если после выполнения этого кода обновления не произошло, тогда можно отлаживать. 
Если все в порядке и структура обновилась ,то только тогда уже лезть в отладку worker .

**Comment by boffart** [comment]
Предполагаю, что проблема вот в этом кэш
`$metaData          = $this->di->get(ModelsMetadataProvider::SERVICE_NAME);`
пока он не обнулится, метаданные старые и таблица не обновляется.
