### ISSUE TITLE
The "delete everything" command does not work correctly on

### ISSUE THREAD

**Issue by atar90** [mikopbx/Core#273]
1. Не удаляются сотрудники;
2. Сопровождается сообщением об ошибке.

![image](https://user-images.githubusercontent.com/87700676/154029633-7a230cd9-28af-44fa-ba23-b377c3376204.png)

Воспроизводится на предрелизе **2022.1.37-dev**

**Comment by jorikfon** [comment]
Мне кажется там была ошибка с установкой модуля, упало API, а удалить все тоже через API работает, другой вопрос что в сообщение об ошибке такое на 500 error

**Comment by jorikfon** [comment]
We should change the default incoming rule and clear the extension on the rule before deleting the extension.
