### ISSUE TITLE
Improve the annoncement after coupon activation

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#274]

**Comment by boffart** [comment]
не хватает какого-то внятного оповещения в интерфейс о том что все ок, активировали купон. Щас оно молча перегружает страницу.

**Comment by jorikfon** [comment]
Чистая станция, ввожу ключ, получаю сообщение об активации купона, это не правильно. Надо проверять ключ или купон ввели.
<img width="443" alt="Screenshot 2022-06-23 at 14 05 53" src="https://user-images.githubusercontent.com/5922918/175285073-0611fe88-a3b2-467a-997b-12a9e57ad83d.png">

**Comment by jorikfon** [comment]
И не отрабатывает релоад страницы, остается форма регистрации на экране.

**Comment by boffart** [comment]
ок, проверю
релод страницы я отключил, добавил запрос на получение lic_info после успеха
информация по новому продукту обновляется на странице

**Comment by jorikfon** [comment]
Там на одной странице у нас регистрация нового ключа, ввод ключа существующего, ввод купона, ввод ключа и купона одновременно.  Хорошо бы все эти сценарии проверить после правки.

**Comment by boffart** [comment]
Проверил. 
ввод ключа и купона одновременно - этот сценарий не возможен. все остальное норм.
