### ISSUE TITLE
динамическое добавление агентов в очередь

### ISSUE THREAD

**Issue by radioteh** [mikopbx/Core#29]
Добрый день. На текущий момент не получается создать очередь без добавления статических агентов в веб-интерфейсе. 
Будет ли реализован функционал динамического добавления (регистрации) агентов в очереди?
Будет ли реализован механизм приоритетов у агентов в очереди?

**Comment by boffart** [comment]
Для 2020.1.124 есть вот такая статья:
Динамические агенты очередей
https://wiki.mikopbx.com/faq:queue_dynamic_agents

**Comment by radioteh** [comment]
да, но при этом невозможно создать пустую очередь, для динамического добавления агентов:
![изображение](https://user-images.githubusercontent.com/50371750/101909058-09e16400-3bce-11eb-9845-40d9ac025f64.png)
и из-за того, что агенту нельзя назначить приоритет (parametr priority у статического агента), добавленный статический агент будет первым в очереди :(
