### ISSUE TITLE
General error: 1 no such table: call_events after upgrade 2022.1.37-dev to 2022.1.86-dev

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#305]
При обновлении рабочей не стартует система, в логе такое.

[27-Mar-2022 15:33:24 Europe/Moscow] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: call_events in /offload/rootfs/usr/www/src/Core/Asterisk/CdrDb.php:67
Stack trace:
#0 [internal function]: PDO->prepare('SELECT MAX("cal...')
#1 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->query('SELECT MAX("cal...', Array, Array)
#2 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, Array, Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->execute(NULL, NULL)
#4 [internal function]: Phalcon\Mvc\Model::groupResult('MAX', 'maximum', Array)
#5 /offload/rootfs/usr/www/src/Core/Asterisk/CdrDb.php(67): Phalcon\Mvc\Model::maximum(Array)
#6 /offload/rootfs/usr/www/src/Core/System/PBX.php(368): MikoPBX\Core\Asterisk\CdrDb::checkDb()
#7 /offload/rootfs/usr/www/src/Core/System/SystemLoader.php(173): MikoPBX\Core\System\PBX->configure()
#8 /offload/rootfs/usr/www/src/Core/Rc/bootup_pbx(28): MikoPBX\Core\System\SystemLoader->startMikoPBX()
#9 {main}
  thrown in /offload/rootfs/usr/www/src/Core/Asterisk/CdrDb.php on line 67

**Comment by boffart** [comment]
done
