### ISSUE TITLE
CDR: Errors in recording call when forwarding a call to a queue

### ISSUE THREAD

**Issue by emassen** [mikopbx/Core#316]
Me again bothering. The correction you mentioned was made, but now I have a different situation. The telephone 5598402XXXX called 5539229450 - FILA 300 - EXTENSION 589 answered, made an assisted transfer with the RAMAL616. Then RAMAL616 talked to 5598402XXXX. The print and verbose of the call follow.
![cdr](https://user-images.githubusercontent.com/93296723/165532862-778f8292-e840-4350-9362-b1082dba50bf.png)
[verbose.txt](https://github.com/mikopbx/Core/files/8572547/verbose.txt)

**Comment by boffart** [comment]
How I tested: 

1. **79257184238** call to **233123**
2. Call route to Queue 2001 
3. 201 answer
4. 201 attended transfer to Queue 2002
5. 202 answer
6. 201 hangup
7. 79257184238 bridge 202
8. 202 hangup

<img width="1115" alt="MikoPBX_История_вызовов" src="https://user-images.githubusercontent.com/5922739/165755684-d282fb72-8e25-4a74-a4eb-1cfe2e6d7807.png">

Similarly to my test, describe how to reproduce the situation

**Comment by emassen** [comment]
My Test:

1. 5598402XXXX call to 5539229450
2. Call route to Queue 300
3. 589 answer
4. 589 attended transfer to Queue 200
5. 606 answer
6. 589 <-> 606 - talk and explain who will be transferred
7. 589 hangup
8. 5598402XXXX bridge 606
8. 606 hangup

**Comment by boffart** [comment]
I don't understand how to repeat it yet. I attached the above, performed a similar test and everything worked fine

**Comment by emassen** [comment]
A point to explain, we don't use IVR calls go directly into a QUEUE.

**Comment by emassen** [comment]
PCAP and verbose log.

5598402XXXX call to 5539229450
Call route to Queue 3000
568 answer
568 attended transfer to Queue 3002
628 answer
568 <-> 628 - talk and explain who will be transferred
568 hangup
5598402XXXX bridge 628
628 hangup

[call.zip](https://github.com/mikopbx/Core/files/8674374/call.zip)
[verbose.zip](https://github.com/mikopbx/Core/files/8674375/verbose.zip)

**Comment by boffart** [comment]
For the **Call Queue**, try increasing the "**Time attempt call to agents**" from **3** seconds to **300**, will the situation change?

**Comment by emassen** [comment]
The current setting is not 3 but 20. As shown on the screen, this is default. But I'll try to put 300 to see how it behaves.
![time-default](https://user-images.githubusercontent.com/93296723/168284198-1b066c13-75db-4e04-83ac-f78a231d35b5.png)

**Comment by boffart** [comment]
Check the value of this parameter for queue 3002.

**Comment by emassen** [comment]
I deleted the queues, left them with default values and even so the third audio doesn't record as well as it doesn't record the history of that connection.

5598402XXXX call to 5539229450
Call route to Queue 3000
568 answer
568 attended transfer to Queue 3002
604 answer
568 <-> 604 - talk and explain who will be transferred
568 hangup
5598402XXXX bridge 604
604 hangup
[pcap-verbose.zip](https://github.com/mikopbx/Core/files/8688727/pcap-verbose.zip)

**Comment by boffart** [comment]
Corrected the error. For edits, see in the [commit](https://github.com/mikopbx/Core/commit/8d8cb4375e70338f40d9f4d9fc2152352c2d66a7).
