### ISSUE TITLE
Does not return busy.

### ISSUE THREAD

**Issue by emassen** [mikopbx/Core#319]
Again, now with another small error, the phones are not returning BUSY, just the busy code. Code: Q.850;cause=16

**Comment by boffart** [comment]
Attach a traffic `Sngrep` dump for analysis

**Comment by emassen** [comment]
Send a pcap file.
[625.zip](https://github.com/mikopbx/Core/files/8594163/625.zip)

**Comment by boffart** [comment]
Ideally, there should be two SIP `625 <---> PBX` and `PBX <---> 638` dialogs.
If there is no second dialog, then verbose logs should be analyzed.
There is only a `625 <---> PBX` dialog in the dump. The PBX returned a 603 Decline response.

**Comment by emassen** [comment]
Below is a file with the two logs.
[638-625.zip](https://github.com/mikopbx/Core/files/8631841/638-625.zip)

**Comment by boffart** [comment]
I have made edits to dialplan. Now, if the subscriber is busy, then when calling his number, the caller will receive a BUSY return code

Edits are available in the [commit](https://github.com/mikopbx/Core/commit/05499d477aa189f577e4dff1e3fce05ea13ec1cc)
