### ISSUE TITLE
Docker: OCI runtime exec failed: exec failed: unable to start container process: read init-p

### ISSUE THREAD

**Issue by kik-krsk** [mikopbx/Core#337]
Столкнулся с проблемой что после запуска в доке контейнере, через какое то время mikopbx перестает работать
```
docker exec -it mikopbx  sh
OCI runtime exec failed: exec failed: unable to start container process: read init-p: connection reset by peer: unknown
```
И в вебке ругается `The storage disk was not connected`
Звонки тоже не проходят
Последняя строчка 
```
docker logs mikopbx
 Start Nginx daemon...................................................DONE
```
```
systemctl status docker.service

May 30 11:49:09 vats dockerd[1960146]: time="2022-05-30T11:49:09.840805492+07:00" level=error msg="stream copy error: reading from a closed fifo"
May 30 11:49:09 vats dockerd[1960146]: time="2022-05-30T11:49:09.844989691+07:00" level=error msg="Error running exec 7657788643d9936bd194bc0f67312e9f50052530b9c34565a051bc1fabcfa7af in
```

**Comment by boffart** [comment]
Опишите какая хост - система используется? На чем запускаете docker?

**Comment by kik-krsk** [comment]
Пробовал на двух разных машинах, одна виртуалка VirtualBox, другая Xen. На обоих
```
cat /etc/debian_version 
11.3
```
На VirtualBox запускал, примером из вики
`docker run --cap-add=NET_ADMIN --net=host --name mikopbx            -v /var/spool/mikopbx/cf:/cf            -v /var/spool/mikopbx/storage:/storage            -e SSH_PORT=23            -e ID_WWW_USER="$(id -u www-data)"            -e ID_WWW_GROUP="$(id -g www-data)"            -it -d --restart always ghcr.io/mikopbx/mikopbx-x86-64`

**Comment by boffart** [comment]
Воспроизводится на актуальной версии MikoPBX?

**Comment by boffart** [comment]
На заметку:
https://stackoverflow.com/questions/12079087/fork-retry-resource-temporarily-unavailable
Проблему воспроизвел однократно.

**Comment by boffart** [comment]
Еще одна схожая по теме статья:
https://ngelinux.com/how-to-limit-processes-fork-retry-resource-temporarily-unavailable-linux/

Схожая так как внутри контейнера возникают ошибки:
`-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable`

**Comment by boffart** [comment]
Не завершается приложение timeout
Пример вызова:
`/usr/bin/timeout 1 asterisk  -rx'core waitfullybooted'`

**Comment by boffart** [comment]
https://habr.com/ru/company/hexlet/blog/248519/
похоже описано решение

**Comment by boffart** [comment]
готово. релиз выпустим в течение месяца
