### ISSUE TITLE
Add special character escaping to employee's full name

### ISSUE THREAD

**Issue by boffart** [mikopbx/Core#346]
Заметили проблему, если у сотрудника в ФИО указать дополнительно фамилию внутри ( ) скобок, астеру становится плохо, при совершении вызова этим орератором, с CLI выкидывает)
Убрали скобки и всё стало нормально)

https://t.me/mikopbx_dev/5720

**Comment by Va-Bank** [comment]
В файлах
sites/admin-cabinet/assets/js/src/main/form.js
sites/admin-cabinet/assets/js/pbx/main/form.js
Есть функция
```
/**
* Возвращщает ИСТИНА, если значение содержит спецсимволы.
* @param value
* @returns {boolean}
*/
specialCharactersExistValidateRule(value) {
  return value.match(/[()$^;#"><,.%№@!+=_]/) === null;
}
```
Я даже в начале запутался. По факту функция возвращает FALSE, если значение содержит спецсимолы. Я сделал тестовую страницу у себя и проверил этот момент.
`console.log(specialCharactersExistValidateRule("Test +="));`
при значении "Test +=" функция возвращает FALSE. Я к чему, хотел добавить возможность использовать некоторые запрещенные символы у себя в Мико, т.к. еще до всех этих обновлений у нас много абонентов написаны именно так.
