### ISSUE TITLE
Add a custom wiki URL to a module.json and put it to the "?" link on module settings page

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#359]
Если нет в JSON файле ссылки, то используется старый механизм открытия вики страницы, если описан в JSON файле, то надо переопределять. Желательно не делать обращения из интерфейса к файлам, а может быть добавить колонку в базу данных с настройками модулей и там хранить эту ссылку в виде JSON структуры.
Не забываем что ссылок на описание модулей может быть несколько под разные языки, соответственно в JSON описании модуля и в базе хранить язык.

**Comment by boffart** [comment]
Пример структуры module.json
```
{
  "developer":"MIKO",
  "moduleUniqueID":"ModulePhoneBook",
  "support_email": "help@miko.ru",
  "version": "%ModuleVersion%",
  "min_pbx_version": "2020.2.757",
  "wiki_links": {
    "ru": {
      "https://wiki.mikopbx.com/module-phone-book": "https://wiki.mikopbx.com/ru/module-phone-book"
    },
    "en": {
      "https://wiki.mikopbx.com/en:module-phone-book": "https://wiki.mikopbx.com/en/module-phone-book"
    }
  }
}
```

Будет выполнено переопределение ссылок.
