### ISSUE TITLE
Customization of wiki links on every PBX page

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#360]
Добавить возможность переопределения стандартного механизма ссылок на Wiki для типовых разделов, не забыть про языки.  Может быть задействовать хранимый JSON на стороне сервера для маппинга ссылок.

**Comment by boffart** [comment]
Допилил. Теперь можно описать файл "/var/etc/wiki-links-LANG.json", где LANG - это код языка.
В файле можнео определить маппинг:
`{
  "https://wiki.mikopbx.com/extensions": "https://wiki.mikopbx.com/extensions6"
}`

Можно полностью пере определить ссылки. 

Теперь можно доработать ежедневную задачу в cron. Чтобы запрашивала с нашего сервера актуальный маппинг для ссылок. Или это уже в другой задаче сделать?

**Comment by boffart** [comment]
Выходит два уровня кастомизации:

1. Описать файлы `src/Common/WikiLinks/'.$this->language.'.json` (требуется доступ к raw.githubusercontent.com)
2. Описать локальные файлы `/var/etc/wiki-links-LANG.json` (наивысший приоритет)
