### ISSUE TITLE
Error code 500 every time when I update MikoCTI4 module from UI

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#361]
Вероятно это была эта ошибка, Sentry ее поймал https://sentry.miko.ru/organizations/miko/issues/6509/

**Comment by jorikfon** [comment]
Вроде пропало, если будет выскакивать переоткрою.

**Comment by jorikfon** [comment]
Эта так и не ушла пока

**Comment by boffart** [comment]
Ранее выполнялось два запроса для скачивания. 

- Первый запрос получал только заголовки для оценки размера файла
- Второй запрос выполнял скачивание файла

Переделал на один запрос. Проблема ушла,  10 из 10 попыток (с откатом до снэпшота после каждой попытки) прошли успешно.

**Comment by jorikfon** [comment]
Надо проверить еще раз, сейчас я словил ошибку при установке из ZIP архива. Со второго раза получилось установить, используется самая последняя MKOPBX ver: 2023.1.199-dev
<img width="1215" alt="Screenshot 2023-03-30 at 11 17 53" src="https://user-images.githubusercontent.com/5922918/228728461-329e05cb-e70f-4e9b-aac1-40318d6803e9.png">

**Comment by jorikfon** [comment]
Сегодня обновил на релиз, начал обновлять модуль и получил 500 ошибку. Обновлял загрузкой из интернета. 
**НО** после обновления страницы, модуль был корректно установлен. Предполагаю, что работать надо с самой 500 ошибкой, она выскакивает у нас по тайм-ауту, когда веб интерфейс не смог, на установленное время тайм-аута получить результат. 
Надо там поковырять, но **не таймаут увеличивать**, а может быть больше вариантов ошибок сделать, когда 500, когда время ожидания вышло, когда еще чего-то в ответ пришло. 
<img width="656" alt="Screenshot 2023-04-06 at 12 38 44" src="https://user-images.githubusercontent.com/5922918/230282884-5563d929-979b-421d-b305-ed5d1862979c.png">
<img width="749" alt="Screenshot 2023-04-06 at 12 39 38" src="https://user-images.githubusercontent.com/5922918/230282904-c4a189d1-2dae-46bc-a989-098c8c85c73e.png">

**Comment by jorikfon** [comment]
`{"jsonapi":{"version":"1.0"},"result":false,"data":[],"messages":["Exception on WorkerApiCommands - Argument 1 passed to MikoPBX\\PBXCoreREST\\Lib\\ModulesManagementProcessor::installModule() must be of the type string, null given, called in \/offload\/rootfs\/usr\/www\/src\/PBXCoreREST\/Lib\/ModulesManagementProcessor.php on line 76"],"function":"","processor":"MikoPBX\\PBXCoreREST\\Workers\\WorkerApiCommands::prepareAnswer","pid":31271,"meta":{"timestamp":"2023-07-17T07:23:35+03:00","hash":"70df5aefdb39f6af3db761226d05f58983318054"}}
`

**Comment by jorikfon** [comment]
Переработан процесс установки, надо смотреть что будет теперь.
