### ISSUE TITLE
Зависает MikoPBX

### ISSUE THREAD

**Issue by Va-Bank** [mikopbx/Core#394]
Машина установлена на виртуалке в Proxmox 7.2-7. После обновления на MIKOPBX ver: 2022.2.102 машина стала зависать раз в два-три дня. Если сделать миграцию с одной ноды на другую, то зависает сразу же.
Можно зайти в shell, нажать на "перезагрузить". Пойдет процесс, на консоль выведется 4-5 строк и на этом машина зависает окончательно. 
Какие логи можно посмотреть? Мы посмотрели файл message, но там ничего интересного не было, что могло бы натолкнуть на сбой.
P.S. На данный момент весь лог message забит сообщениями zabbix. Даже архива не осталось за эти пару дней. Придется ждать следующего зависания

**Comment by boffart** [comment]
я бы сперва попробовал понять, проблема связана с конкретной виртуалкой или с MikoPBX
создайте новую ВМ, установите туда чистую MIkoPBX
зависнет ли она? 

если не будет зависать, накатите на нее конфиг своей АТС (можно вырубить сеть, чтобы работе не мешала)
зависнет ли она?

если не будет зависать, попробуйте использовать эту машину вместо старой
будет ли зависать?

**Comment by Va-Bank** [comment]
Установили новую версию с нуля. Пока никаких зависаний. Миграция туда-сюда не вызывает проблем. Сейчас решил раскатать конфигруацию с зависающей машины. Тестируем дальше.

**Comment by boffart** [comment]
пока закрываю, откройте снова, если проблема проявит себя

**Comment by vladikph** [comment]
> Машина установлена на виртуалке в Proxmox 7.2-7. После обновления на MIKOPBX ver: 2022.2.102 машина стала зависать раз в два-три дня. Если сделать миграцию с одной ноды на другую, то зависает сразу же. Можно зайти в shell, нажать на "перезагрузить". Пойдет процесс, на консоль выведется 4-5 строк и на этом машина зависает окончательно. Какие логи можно посмотреть? Мы посмотрели файл message, но там ничего интересного не было, что могло бы натолкнуть на сбой. P.S. На данный момент весь лог message забит сообщениями zabbix. Даже архива не осталось за эти пару дней. Придется ждать следующего зависания

Как разрешилась данная проблема? У меня то же самое.

**Comment by Va-Bank** [comment]
С нуля создал новую VM. Установил чистую MIKOPBX ver: 2022.2.102. Залили туда из бекапа конфигурацию. На сегодняшний день машина ни разу не зависла. Сейчас специально сделал миграцию с одной ноды на другую и обратно. Даже пинги не прерывались. Shell работает - не зависает. Вебка работает - не зависает. Регистрация номеров есть.
P.S.1 Но есть одно но. Я после чистой установки делал миграцию для проверки, а вот после раскатывания конфигурации из бекапа, по-моему нет - забыл. Так что после сегодняшней миграции надо еще последить за машиной - зависнет или нет.
P.S.2 Мико я не обновлял на версию 2022.3.15

**Comment by vladikph** [comment]
> С нуля создал новую VM. Установил чистую MIKOPBX ver: 2022.2.102. Залили туда из бекапа конфигурацию. На сегодняшний день машина ни разу не зависла. Сейчас специально сделал миграцию с одной ноды на другую и обратно. Даже пинги не прерывались. Shell работает - не зависает. Вебка работает - не зависает. Регистрация номеров есть. P.S.1 Но есть одно но. Я после чистой установки делал миграцию для проверки, а вот после раскатывания конфигурации из бекапа, по-моему нет - забыл. Так что после сегодняшней миграции надо еще последить за машиной - зависнет или нет. P.S.2 Мико я не обновлял на версию 2022.3.15

Спасибо, буду пробовать.
