### ISSUE TITLE
Call Logs and Recordings.

### ISSUE THREAD

**Issue by emassen** [mikopbx/Core#395]
I still can't get a logical sequence to the problem, but not all calls are being recorded. Sometimes (not always) transferring a group to an extension stops recording. The previous problem was solved then 80%. If the problem occurs with someone else, we could evolve the solution 100%. Thanks.

**Comment by boffart** [comment]
Which version of the PBX is currently in use?

**Comment by emassen** [comment]
MikoPBX 2022.2.102 
https://github.com/mikopbx/Core/issues/307 Fix the error of recording the call history. When the call arrived at the queue and the subscriber tried attended transfer the call to another queue, the conversation was not recorded.

This error that we discussed in the previous version that was fixed, but it still seems that there are some situations that it occurs the same problem. 80% is now OK. But there's still something strange.

**Comment by emassen** [comment]
119460986XX - QUEUE 3000 - EXT 556
TRANSFER - QUEUE 3002 - EXT 556 -> TALK <- EXT 628
EXT 628 TALK 119460986XX
[verbose-ligacao.txt](https://github.com/mikopbx/Core/files/9403310/verbose-ligacao.txt)

**Comment by boffart** [comment]
According to the log there should be two mp3 audio files

**PJSIP/556-0001b1bf** - 
`ls -l /storage/usbdisk1/mikopbx/astspool/monitor/2022/08/23/09/mikopbx-1661256600.197270_soCP4X.*`
start "2022-08-23 0**9:10:02**", end "2022-08-23 0**9:11:12**"

**PJSIP/628-0001b219** - 
`ls -l /storage/usbdisk1/mikopbx/astspool/monitor/2022/08/23/09/mikopbx-1661256744.197471_i3o142.*`
start "2022-08-23 0**9:12:39**", end 2022-08-23 0**9:13:11**

Check if these files exist, with what extension?

**Comment by emassen** [comment]
~# ls -l /storage/usbdisk1/mikopbx/astspool/monitor/2022/08/23/09/mikopbx-1661256600.197270_soCP4X.*
-rw-r--r-- 1 root root 280224 Aug 23 09:11 /storage/usbdisk1/mikopbx/astspool/monitor/2022/08/23/09/mikopbx-1661256600.197270_soCP4X.mp3
~# 

~# ls -l /storage/usbdisk1/mikopbx/astspool/monitor/2022/08/23/09/mikopbx-1661256744.197471_i3o142.*
-rw-r--r-- 1 root root 127296 Aug 23 09:13 /storage/usbdisk1/mikopbx/astspool/monitor/2022/08/23/09/mikopbx-1661256744.197471_i3o142.mp3
~#

**Comment by boffart** [comment]
Corrected the error.  According to your log, the number "**604**" was **busy**, the PBX did not try to call him, as a result, the PJSIP/604 channel was not created, this caused the CDR filling problem.

The error could occur when one of the queue agents is **busy**

A description of the edit is available at the link
https://github.com/mikopbx/Core/commit/2568db4a117a5122821e83bfde68f0eaef18ecc9
