### ISSUE TITLE
Add extra message to serial console when system fully loaded.

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#403]
Надо чтобы в серийной консоли после  - Start Nginx daemon.................................................. DONE  
была еще одна строчка, что нить типа

- All services are fully loaded
- Open web browser and visit https://80.80.80.81

Это можно сделать?  Мы же знаем наш адрес станции уже?

**Comment by boffart** [comment]
Сделал так:
`- All services are fully loaded   

   The web interface is available at the addresses:

    - https://10.130.0.22:443

   The web interface is available at the external addresses:

    - https://boffart.ru:443
    - https://178.154.243.193:443
`
