### ISSUE TITLE
Consider about H.323

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#406]
Это кодек или протокол? Пишут что может помочь тем кто съезжает с аваи и таких сотни тысяч абонентов

**Comment by boffart** [comment]
Посмотрим, что с этим сделать можно. Нужно изучить тему

**Comment by nevian427** [comment]
Это протокол. Обеспечивается модулем addons/chan_ooh323.
Вряд ли поможет авайкам - они используют свою вариацию внутреннего протокола (те внутри 323 гоняют свой закрытый сигналинг). Но авайки можно шить в сип и так работать.
h.323 нынче у оконечных клиентов не популярен, но у некоторых старых крупных провадеров в сетях мог сохраниться ибо гораздо более стандартизирован и много специфичных телефонных фич.

**Comment by boffart** [comment]
вот есть сомнения нужно ли вообще с H.323 заморачиваться. 

1. запросов от клиентов по этому протоколу нет. 
2. Не ясно как это тестировать, как такой стенд поднять, разве что какой нить Freeswitch поставить или еще один астер. 

очень сомнительное удовольствие.

**Comment by boffart** [comment]
модуль H.323 собрался без проблем
на текущий момент можно собрать только **chan_ooh323**. 
напрягает сообщение в описании конфиг файла "This module is currently unsupported.  Use it at your own risk."

есть все шансы, что будут проблемы.

**Comment by ogursoft** [comment]
Как сделать маршрутизацию по каналу h323. В настройках маршрута требуется провайдер. А провайдер можно добавить только sip и iax. Требуется для направления звонков на Avaya IP Office, т.к. SIP каналов там нету.

**Comment by boffart** [comment]
Идея кастомизации описана тут
https://wiki.mikopbx.ru/faq:dongle#isxodjaschie
```
[SIP-1619606129-outgoing-custom]
exten => _[0-9*#+]!,1,Set(DIAL_COMMAND=Dongle/dongle0/${number})
	same => n,return
```

**Comment by ogursoft** [comment]
Извиняюсь, все получилось, транк настроил.
