### ISSUE TITLE
When the module is activated, update the interface

### ISSUE THREAD

**Issue by boffart** [mikopbx/Core#407]
При включении модуля неплохо бы интерфейс перегружать автоматом. 
А то включил, смотрю в боковое меню и не вижу изменений. Оказывается надо обновить всю страницу.

**Comment by jorikfon** [comment]
Там же сообщения включения выключения есть, например модуль маршрутизации показывает какие правила изменены и на что, если обновишь страницу этого уже не будет видно. А зачем тебе сбоку что-то видеть если ты как раз уже в интерфейсе модуля?

Можно наверное AJAX добавлять удалять меню или обновлять только блок меню, получив его AJAX запросом в фоне.
