### ISSUE TITLE
In Queue with strategy fewestcalls call doesn't go to next agent

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#409]
MikoPBX 2022.3.15

Звонок поступает в очередь со стратегией fewestcall (Вызов поступает на участника очереди, который меньше всего обработал вызовов). Звонит только агент, который меньше всего принял вызовов, на других агентов вызов не переходит.

**Comment by boffart** [comment]
Мб это нормально? )) Действительно астер сперва будет до упора звонить агенту, который меньше всего говорил с клиентами. До упора... 

Можно реализовать каскад из очередей, если до наименее загруженного не дозвонились, то направить звонок на следующую очередь. 

Либо пытаться допилить очередь, к примеру управлять значением пенальти....

**Comment by boffart** [comment]
https://wiki.mikopbx.ru/call-queues#raspredelenie_zvonkov
дополнил документацию
