### ISSUE TITLE
Найден баг при создании исходящего маршрута

### ISSUE THREAD

**Issue by alglyzin** [mikopbx/Core#41]
Не принимает шаблон "*914*"
Хотя символ "*"находится в списке разрешенных.

![2021-01-07_22-35-35](https://user-images.githubusercontent.com/11249756/103936949-245d1d80-5139-11eb-9181-018c6bfbf346.png)

**Comment by boffart** [comment]
Будет доработано в новой версии. 
Код задачи ASK-896.
