### ISSUE TITLE
Cycle of opening page for change web administrator pass in new release 2022.3.15

### ISSUE THREAD

**Issue by Realmagnum** [mikopbx/Core#412]
Hello.

Поставил вчистую **2022.3.15**
Вошел, поменял пароль по умолчанию, пробую дальше настраивать. 
А меня постоянно снова перекидывает на страницу изменения пароля, _http://IP/admin-cabinet/general-settings/modify/#/passwords_ 

Разлогинился, вошел с новым паролем - то же самое.
Перегрузил PBX - то же самое. 
Поменял снова пароль на сложный сгенерированный - то же самое…
Пример второго сложного пароля - 4DTgL3iywWR71Pdk.
Первый был попроще, но тоже содержал буквы нижнего и верхнего регистра + цифры - если эти условия не соблюдаются, система не позволяет его сохранить. 
И с этими двумя паролями я входил в админку как положено… 
На SSH тоже менял на сложный, также пробовал отключать вход по паролю - перебрасывает. 
В другом браузере поведение аналогичное.
Сделал сброс пароля через пункт 7. Вошел со стандартным, установил новый вида q3UUft8Xng7BJU. Не помогло.
Смотрю на сообщение 
«Не используйте стандартный логин и пароль администратора системы»… А вдруг смена имени администратора поможет - изменил, не помогло…

**Comment by boffart** [comment]
Я проверил на **vmware** fusion, на **virtualbox**. Проблема не воспроизводится. Браузер от yandex. 
Можете прислать выгрузку виртуальной машины для анализа?

**Comment by Realmagnum** [comment]
> Я проверил на **vmware** fusion, на **virtualbox**. Проблема не воспроизводится. Браузер от yandex. Можете прислать выгрузку виртуальной машины для анализа?

К сожалению уже нет. Полностью удалил  vhdx и пересоздал ВМ заново.

**Comment by Realmagnum** [comment]
Если не будут других случаев - скорей всего проблемы браузера или куков.

**Comment by boffart** [comment]
Если воспроизведется, то пришлите выгрузку машины. 
Я не могу воспроизвести. задачу пока закрываю.
