### ISSUE TITLE
Docker. Module installation error

### ISSUE THREAD

**Issue by boffart** [mikopbx/Core#416]
https://qa.mikopbx.ru/13087/запуска-mikopbx-docker-сообщение-подключен-хранения-настроек

**Comment by napaster** [comment]
Присоединяюсь к проблеме. Такие же проблемы. Не могу поставить модули, не  видит диск для записей.

**Comment by napaster** [comment]
Выглядит так, что не хватает каких то прав на дирректорию какую нибудь, или что-то подбное. Хотя сам модуль скачивается в /var/spool/mikopbx/storage/usbdisk1/mikopbx/custom_modules

![изображение](https://user-images.githubusercontent.com/10761151/196094462-a60814d6-f7dd-4fb0-af1d-a5ff5d46afd2.png)

**Comment by boffart** [comment]
Ошибку воспроизвел и поправил. Для исправления, в контейнере можно вручную поправить скрипты как описано в "[ee294dc](https://github.com/mikopbx/Core/commit/ee294dc43f7db161b3195bfcab1c1b3e55d61e47)" и [9ebae4e](https://github.com/mikopbx/Core/commit/9ebae4e3297dc9de8aba403e7ec58d83812b374f).

**Comment by napaster** [comment]
А релиз когда будет с этим патчем ?

**Comment by boffart** [comment]
Я надеюсь, что в течение месяца, графика релиза как такового нет. Выпускаем как только наберется более менее большой объем решенных задач.
