### ISSUE TITLE
UEFI boot

### ISSUE THREAD

**Issue by napaster** [mikopbx/Core#420]
Доброго времени суток. Очень не хватает поддержки UEFI, многие современные десктопы и прочие девайсы уже перестают поддерживать Legacy в принципе. Отсюда проблема в использовании и инсталяции дистрибутива в принципе. Что очень сильно ограничивает использование. Когда будет реализован функционал с поддержкой UEFI ?

**Comment by boffart** [comment]
Уже есть обсуждение на эту тему
https://github.com/mikopbx/Core/discussions/276

Пока ничего не изменилось. Трудозатраты требуются большие, энтузиастов и спонсоров пока нет

**Comment by napaster** [comment]
Это конечно здорово, что вы закрыли задачу. В планах то это вообще есть ? или нет ?

**Comment by boffart** [comment]
В ближайших планах этого нет. Помним, периодически возвращаемся к этому вопросу, но пока не вижу реальной необходимости в этом функционала. За весь период существования проекта было всего два подобных запроса.
