### ISSUE TITLE
Вопросы по docker

### ISSUE THREAD

**Issue by napaster** [mikopbx/Core#421]
Поставил чистую систему centos 8 stream, без графики без всего. В ней запустил docker. Есть пара вопросов по документации. 
У вас в мануале написано 
```# Вариант запуска MikoPBX
# НЕ привилегированный режим. Пользователь и группа "www-data" дожены существовать в системе:
docker run --cap-add=NET_ADMIN --net=host --name mikopbx \
           -v /var/spool/mikopbx/cf:/cf \
           -v /var/spool/mikopbx/storage:/storage \
           -e SSH_PORT=23 \
           -e ID_WWW_USER="$(id -u www-data)" \
           -e ID_WWW_GROUP="$(id -g www-data)" \
           -it -d --restart always ghcr.io/mikopbx/mikopbx-x86-64
```
Вопрос а если у меня нету этого пользователя и группы ? как быть тогда ? это обязательная опция или нет ? и на что влиеяет ?

**Comment by boffart** [comment]
Вопросы следует задавать в дискуссиях. Текущий раздел предназначен для описания задач по доработке. 

если пользователя www-data нет, то создайте его или используйте любого другого пользователя с ограниченными правами  (не root)
