### ISSUE TITLE
Incorrect visual behavior of play button in web interface

### ISSUE THREAD

**Issue by Realmagnum** [mikopbx/Core#432]
При нажатии на кнопку воспроизведения и после окончания воспроизведения - кнопка остается в виде паузы и не меняет свое состояние обратно.
![photo_2022-11-07 02 31 38](https://user-images.githubusercontent.com/28831241/200201440-914f5f68-589e-4bfe-8048-60ca6f174d73.jpeg)

**Comment by boffart** [comment]
В каком браузере воспроизводится проблема? 
Я проверил в yandex браузере, все ок
В safari воспроизвелось

**Comment by boffart** [comment]
Поправил. Проверил работу в safari и chrome
