### ISSUE TITLE
Bugs in "Mail settings" - "template - missed calls"

### ISSUE THREAD

**Issue by Realmagnum** [mikopbx/Core#433]
1. Почему **в теме** **не происходит** замена переменной, а в теле письма работает корректно?
Вообще неполноценно как-то. Похоже на баг. 
![photo_2022-11-07 02 41 24](https://user-images.githubusercontent.com/28831241/200201866-acc61dd5-e7f5-42d3-994c-36a5ed6fefd7.jpeg)

2. И во времени хорошо бы отрезать вывод дополнительного блока цифр после секунд во времени… В шаблоне голосовой почты он не выводится.
см. первый скриншот.

4. Так же некорректно выводит текст из подвала пропущенных сообщений, **проглатывает переводы строки**. Из аналогичного подвала голосовой почты все ОК. Пришлось подпись оставить в основном блоке, там не проглатывает переводы строки. Явно баг.
![photo_2022-11-07 02 42 41](https://user-images.githubusercontent.com/28831241/200201938-0e9d4205-0561-45b0-8429-5b1b909e7954.jpeg)

5. Почему-то в голосовой почте **переменная ${VM_CALLERID}**  выводит целиком ИМЯ+НОМЕР в виде "Фамилия Имя" <номер>, а вот в шаблоне пропущенных вызовов - **паттерн NOTIFICATION_CALLERID** выводит только номер…
![photo_2022-11-07 02 45 14](https://user-images.githubusercontent.com/28831241/200202052-f9e33573-4902-49f8-a6f9-87bb420fff04.jpeg)
**Не баг, но хотелось бы подстановки ИМЕНИ для внутренних номеров и известных номеров из Телефонной книги.** 

6. Почему-то **нет единообразия** в оформлении вида заменяемых переменных в шаблонах пропущенных звонков и голосовой почты? 
 Нелогично и некрасиво.
**${VM_CALLERID} против NOTIFICATION_CALLERID...**

**Comment by boffart** [comment]
1. Замена в теме изначально не была предусмотрена, о чем было написано в документации на wiki. Доработал. 
2. Поправил
3. Поправил
4. Доработал. Добавил новые перeменные "**VM_CALLER_NAME**" и "**VM_CALLER_NUM**"
5. Нет единообразия тк как это совершенно разные модули. Так исторически сложилось. Кое что унаследовали от Askozia. Модули разрабатывались в разное время. Имена переменных будут отличаться. 

Коммит с доработками прикрепил к этой задаче.
