### ISSUE TITLE
Divide iptables block according to fail2ban category

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#434]
Чтобы если идет подбор по SIP не блокировать веб интерфейс, много раз получалось у нас словить блок из сети только из за того что телефон был со старым паролем. А чтобы исправить ситуацию ни по SSH ни через WEB уже не зайти... Может быть при подборе по WEB блокировать веб, а при подборе по SIP блокировать SIP. 

По хорошему наверное достаточно 4 отдельных порта для блокировки. Веб, SSH, SIP-IAX-RTP, AMI

У нас вроде есть в Fail2BAN категории. А при входе в интерфейс с адреса на котором стоит какая-то блокировка в колокольчике бы показывать, что для вашего IP установлено ограничение для AMI или для SIP, разбирайтесь. 

Особенно когда станция в Яндекс облаке, а телефон в локальной сети за NAT, прямо в лет ловится тотальный блок.

**Comment by boffart** [comment]
Готово
