### ISSUE TITLE
ARI, dialplan и интеграция asterisk с бордой техподдержки Omnidesk в рамках MikoPBX

### ISSUE THREAD

**Issue by ogt111** [mikopbx/Core#435]
Вот неожиданно нарисовалась одна беда. И из-за нее не хочется возвращаться на нативный астериск. А тут задачу поставили. Создал очередь для группы технической поддержки, а они еще и используют omnidesk, как таск борду. И затребовали интеграцию с ним. Там имеется интеграция с asterisk и там как раз нужен ARI и модификация dialplan.

https://support.omnidesk.ru/knowledge_base/item/248033?sid=4/#scroll_to_0

Вот и никак не могу задействовать ARI. Даже конфига нет. И как правильно модифицировать dialplan, ну никак не одолею. :-(

**Comment by boffart** [comment]
Боюсь это задачка "со звездочкой". 
Тут сходу и не решить, у нас нет планов запуска ARI, нет инструкций по его использованию в dialplan,  а там реально много чего может потребоваться. 

Лучше перенести это в [обсуждения](https://github.com/mikopbx/Core/discussions)
