### ISSUE TITLE
Ошибка входящей маршрутизации

### ISSUE THREAD

**Issue by bl00d1ce** [mikopbx/Core#436]
Если создать только одно правило, в котором указать условие "Любой провайдер", вызов не проходит. Версия АТС: 2022.3.15

**Comment by boffart** [comment]
Работа корректная. Просто не надпись следует скорректировать "Любой провайдер" - она вводит в заблуждение. 
На самом деле такие правила входящей маршрутизации относятся только к вызовам без авторизации, так называемые звонки по SIP URI, вызовы, которые не привязаны к конкретному "провайдеру"
