### ISSUE TITLE
При использовании docker плодятся zombie

### ISSUE THREAD

**Issue by borisk1976** [mikopbx/Core#437]
2022.3.15 - плодятся zombie при использовании docker с ужасающей скоростью.
За час работы - 467 zombie
За 3-4 дня разрастается до 4000-5000
Все вот такого плана:
root      631000  0.0  0.0      0     0 ?        Zs   13:38   0:00 [timeout] <defunct>
root      631056  0.0  0.0      0     0 ?        Z    13:39   0:00 [php] <defunct>
root      631083  0.1  0.0      0     0 ?        Z    13:39   0:00 [php] <defunct>
root      631111  0.1  0.0      0     0 ?        Z    13:39   0:00 [php] <defunct>
root      631134  0.0  0.0      0     0 ?        Z    13:39   0:00 [php] <defunct>
root      631163  0.1  0.0      0     0 ?        Z    13:39   0:00 [php] <defunct>
root      631640  0.0  0.0      0     0 ?        Z    13:39   0:00 [bash] <defunct>
root      631641  0.0  0.0      0     0 ?        Z    13:39   0:00 [bash] <defunct>
root      631643  0.0  0.0      0     0 ?        Zs   13:39   0:00 [ntpd] <defunct>
root      631658  0.0  0.0      0     0 ?        Zs   13:39   0:00 [timeout] <defunct>
root      631709  0.8  0.0      0     0 ?        Z    13:40   0:00 [php] <defunct>
root      631737  1.0  0.0      0     0 ?        Z    13:40   0:00 [php] <defunct>
root      631764  1.0  0.0      0     0 ?        Z    13:40   0:00 [php] <defunct>
root      631786  1.1  0.0      0     0 ?        Z    13:40   0:00 [php] <defunct>
root      631818  1.1  0.0      0     0 ?        Z    13:40   0:00 [php] <defunct>

Система Debian 11.5

На VM версии такого не наблюдается

**Comment by boffart** [comment]
Проблема известна. Возникает из за того, что корневой процесс - php. 
Поправили в последний коммитах, entrypoint теперь будет запускаться как shell процесс. и zombie больше не будет.

**Comment by boffart** [comment]
https://github.com/mikopbx/Core/issues/337
вот ссылка на задачу и коммиты с решением проблемы.
