### ISSUE TITLE
Use alphanumeric DID number in Incoming routing rule as normal extension instead of pattern

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#439]
MikoPBX 2022.3.15

При добавлении входящего маршрута в символьной строкой в поле DID, в контекст эта строка будет добавлена как шаблон.
Необходимо добавить проверку, если в поле DID указан шаблон, то добавлять его как шаблон, если цифро-буквенная строка, то как обычный экстеншен

**Comment by boffart** [comment]
поправил
