### ISSUE TITLE
Не отображается номер в уведомлении об ошибке

### ISSUE THREAD

**Issue by TheShadowAngel** [mikopbx/Core#454]
Не отображается внутренний номер, для которого появляется ошибка:

![изображение](https://user-images.githubusercontent.com/41905618/212684369-f599872b-608f-4cf3-8c20-435fab0f0338.png)

**Comment by boffart** [comment]
Как воспроизвести? 
Для всех номеров указан сложный пароль?

**Comment by TheShadowAngel** [comment]
На старой версии, видимо, сложность паролей не проверялась, а после обновления вылезла эта ошибка :)
Только на одном номере пароль был простой, поправил - ошибка ушла 👍🏻

**Comment by boffart** [comment]
Поправил.
