### ISSUE TITLE
Не правильная точка монтирования про использовании Docker

### ISSUE THREAD

**Issue by napaster** [mikopbx/Core#479]
При использовании docker директория /var/spool/mikopbx/storage остается пустой. Ошибка происходит в версии MIKOPBX ver: 2023.2.224 при использованиие в окружении Docker.
Имеется свеже установленный Debian 11
`cat /etc/debian_version
11.6`
Docker
`docker --version
Docker version 23.0.3, build 3e7cbfd`

Воспроизведение:
Установка докер и его запуск стандартная процедура, описывать не имеет смысла. 

1.  mkdir -p /var/spool/mikopbx/cf 
2.  mkdir -p /var/spool/mikopbx/storage
3. docker pull ghcr.io/mikopbx/mikopbx-x86-64
4. docker run --cap-add=NET_ADMIN --net=host --name mikopbx \
           -v /var/spool/mikopbx/cf:/cf \
           -v /var/spool/mikopbx/storage:/storage \
           -e SSH_PORT=23 \
           -e ID_WWW_USER="$(id -u www-data)" \
           -e ID_WWW_GROUP="$(id -g www-data)" \
           -it -d --restart always ghcr.io/mikopbx/mikopbx-x86-64

далее проверяем путь /var/spool/mikopbx/storage и там будет пусто. 

Лечится достаточно просто: меняется mountpoint

`docker run --cap-add=NET_ADMIN --net=host --name mikopbx \
           -v /var/spool/mikopbx/cf:/cf \
           -v /var/spool/mikopbx/storage:/mountpoint \
           -e SSH_PORT=23 \
           -e ID_WWW_USER="$(id -u www-data)" \
           -e ID_WWW_GROUP="$(id -g www-data)" \
           -it -d --restart always ghcr.io/mikopbx/mikopbx-x86-64`

То есть меняется `-v /var/spool/mikopbx/storage:/storage` на `-v /var/spool/mikopbx/storage:/mountpoint`

Возможно бага или еще что-то.

**Comment by boffart** [comment]
https://github.com/mikopbx/Core/commit/1dc1430fa498d80c3f9d751d4c51bf0896db54ec

**Comment by boffart** [comment]
Попробуйте:

```
curl 'https://files.miko.ru/s/iPiBXNgcrS5asXB/download' -O 2023.2.1-mikopbx-generic-x86-64-linux.tar;
cat 2023.2.1-mikopbx-generic-x86-64-linux.tar | docker import  --change 'ENTRYPOINT ["/bin/sh", "/sbin/docker-entrypoint"]' - mikopbx:latest
docker run --cap-add=NET_ADMIN --net=host --name mikopbx \
           -v /var/spool/mikopbx/cf:/cf \
           -v /var/spool/mikopbx/storage:/storage \
           -e SSH_PORT=23 \
           -e ID_WWW_USER="$(id -u www-data)" \
           -e ID_WWW_GROUP="$(id -g www-data)" \
           -it -d --restart always mikopbx:latest
```
Ошибка должна уйти. 
Чтобы исправить ошибку, можно взять из релиза прикрепленный tar файл. 
Поправить в нем анлогично коммиту https://github.com/mikopbx/Core/issues/479#:~:text=3%20minutes%20ago-,1dc1430,-Write
далее импортировать образ:
`cat mikopbx*.tar | docker import  --change 'ENTRYPOINT ["/bin/sh", "/sbin/docker-entrypoint"]' - mikopbx:latest`

**Comment by napaster** [comment]
Отлично. Патч помогает.
