### ISSUE TITLE
Сетевые параметры

### ISSUE THREAD

**Issue by kik-krsk** [mikopbx/Core#482]
При запуске в докер без ключа --net=host, параметры на вкладке Сетевые параметры не отображаются и не изменяются, в частности: Внешний IP адрес вашего маршрутизатора

![Screenshot_20230424_103416](https://user-images.githubusercontent.com/101323028/233894640-95af510b-5c79-4259-99d0-432fe19ad72f.png)

Так же при переменной GNATS_PORT при старте контейнера, внутри контейнер продолжает слушаться пор 4223
/ # netstat -tunlp | grep gnats
tcp        0      0 :::4223                 :::*                    LISTEN      5811/gnatsd
tcp        0      0 :::8223                 :::*                    LISTEN      5811/gnatsd

**Comment by boffart** [comment]
Запуск без ключа --net=host не тестировался. у этого режима слишком много ограничений .
К примеру невозможно было пробросить диапазон портов, больший чем 100. 
Для нашего docker контейнера вообще не предусмотрено изменение и настройка сетевых интерфейсов, эти параметры должны настраиваться на хост мащшине.

**Comment by kik-krsk** [comment]
В релизе 2022.3.15 параметры на вкладке работали. Кроме 100 портов какие ещё ограничения? 
Можете описать какие  параметры меняются при указании внешнего ИП адреса на этой вкладке?

**Comment by boffart** [comment]
"Внешний адрес" влияет только на формирование транспорта в pjsip.conf, описывается опция exterip. 
Больше ни на что он не влияет. 

По ограничениям docker Вам лучше обратиться к их документации. Что не нравится мне:

1. +1 NAT
2. Органичение на проброс портов
3. При большом количестве проброшенных портов создается огромное количество правил iptables, что увеличит нагрузки на ЦП, об этом много обсуждений в сети.
