### ISSUE TITLE
If the restrictions on non-working time routes are maintained, the daws in another rule are disabled

### ISSUE THREAD

**Issue by boffart** [mikopbx/Core#483]
А подскажите такой момент. Вот есть нерабочее время. И там когда заходишь в какой то из пунктов, можно выбрать ограничение по маршрутам. Так вот DID там почему то сбивается. То есть я выбираю ограничение по маршрутам допустим в одном нерабочем времени, нажимаю сохранить, потом иду в другой диапазон делаю то же самое, потом возвращаюсь в предыдущее и там все неактивно стало опять.

**Comment by napaster** [comment]
Если будет патчик, можно будет для докера сразу сделать ?

**Comment by boffart** [comment]
Нет возможности применить два разных правила нерабочего времени к одному и тому же маршруту.

**Comment by napaster** [comment]
Это баг или так и должно работать ? как тогда предусмотреть ? То есть суть в чем. Есть куча входящих маршрутов. И они работают по разному. Офис работает с 8 до 17 с понедельника по четверг и с 8 до 16 в пятницу. Есть так же 2 линии которые которые для гословой почты. они работать должны всегда.  Но получается что если начинает расставлять галочки, то остальыне правильна не работают

**Comment by boffart** [comment]
Это баг, смотрите коммит, https://github.com/mikopbx/Core/issues/483 можно поправить вручную. 
В ближайшие пару недель выпустим релиз с правками.
