### ISSUE TITLE
Fix Z index for popup or menu, or fix message width

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#486]
<img width="1036" alt="Screenshot 2023-04-28 at 16 42 04" src="https://user-images.githubusercontent.com/5922918/235100081-6827e61b-453f-4dd4-b450-feb984fbd2c3.png">
Подправить максимальный размер всплывашки

**Comment by boffart** [comment]
С z-index все в порядке, для popup он 1900
Для слайд меню он 102. дело в чем то другом
