### ISSUE TITLE
Auto backup 7 last days of config DB to storage

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#487]
В составе MikoPBX сделать автобекап воркер, чтобы сохранял последние 7 дней конфиг базы данных из CF раздела, раз в день.

Перед обновлением из IMG сделать еще один автобекап базы данных на диск для хранения.

При старте АТС, если конфиг системы оказался дефолтный( можно по MD5 проверить)  то автоматом восстановить последний с storage вариант конфигурации из диска для хранения.

При нажатии кнопки удалить все в общих настройках, удалить также все бекапы конфигураций.

Может снять всякие проблемы при обновлении однодисковых, многодиюсковых конфигураций, может помочь с падением базы данных и всяких других бедах.

**Comment by jorikfon** [comment]
Конечно на Storage и делать, можно в mikopbx-settings.json добавить core.cfBackupDir  = /mountpoint/mikopbx/cf_backup
 
 и потом используя этот параметр делать туда бэкапы периодически, ну и при обновлении тоже туда.

**Comment by boffart** [comment]
Поправить работу в скрипте:
http://github.com/mikopbx/Core/blob/cbf695ce64faca0010083b030fba1cb78d46d6de/resources/rootfs/sbin/pbx_firmware#L74-L74

**Comment by jorikfon** [comment]
Какие ты ошибки сыпятся после обновления из img
![Uploading Screenshot 2023-06-20 at 12.52.58.png…]()

**Comment by boffart** [comment]
Поправил.
