### ISSUE TITLE
Оповещение о записи разговора

### ISSUE THREAD

**Issue by humingos** [mikopbx/Core#49]
Было бы отлично, если бы система позволяла уведомлять в начале разговора о записи разговора.
Вижу это так.

В системе есть возможность указать какой-то звуковой файл, который будет воспроизводиться в начале каждого разговора. Есть галочка, которая регулирует, надо ли воспроизводить файл при внутренних звонках.

Воспроизведение начинается только и сразу после начала разговора, т.е. после того, как отвечающая сторона подняла трубку. Воспроизводимый файл должен быть слышен обоим сторонам. В идеале воспроизведение должно идти прям в сам разговор, т.е. по сути разговаривать можно уже на фоне воспроизводимого файла. Воспроизводимый файл должен попадать и в запись разговора.

**Comment by boffart** [comment]
Подобные планы есть. Мб. опишем блог на эту тему. 
Основаная проблема нехватка времени, потому по срокам сориентировать не могу.
