### ISSUE TITLE
CallGroup *8 Deny

### ISSUE THREAD

**Issue by emassen** [mikopbx/Core#490]
After updating the user group module, I can no longer pull calls with *8. I believe it's something in the group with permissions now.

**Comment by boffart** [comment]
See 
https://github.com/mikopbx/ModuleUsersGroups/blob/f5f0a1fa17befd5fdecebbe93d9ab6ac3e704a2f/Lib/UsersGroupsConf.php#L183-L183

Each user group is a separate call_group, for this reason *8 works only within the group

https://github.com/mikopbx/ModuleUsersGroups/issues

It is better to describe tasks by user groups in the appropriate repository
