### ISSUE TITLE
how to change sound gobal ?

### ISSUE THREAD

**Issue by batboyboy1990** [mikopbx/Core#493]
Я думаю, у нас должен быть FILEmanger для изменения аудиофайла GSM по умолчанию.

**Comment by jorikfon** [comment]
Вы можете через SSH выполнить remount-offload, после этого через WinSCP менять любые файлы в папке /offload/asterisk/sounds/

"You can perform remount-offload via SSH, after which you can use WinSCP to modify any files in the /offload/asterisk/sounds/ directory."
