### ISSUE TITLE
Add flag markers to define T2ISO, Docker, Debian 

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#497]
И дописать функцию определения окружения используя файлы маркеры.
Чтобы можно было однозначно понять в каком окружении сейчас запущена MikoPBX.
Вероятно это надо в TeamCity на этапе сборки образов доработать создание файлов маркеров, + доработать функцию Util::isT2SdeLinux() на поиск файла, а не то, что сейчас там.

**Comment by boffart** [comment]
/etc/t2-sde-build

**Comment by boffart** [comment]
Готово
