### ISSUE TITLE
Fix error on install from ISO after refactoring the class

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#529]

**Comment by jorikfon** [comment]
Делаю

**Comment by boffart** [comment]
обновление из ISO норм отработало

**Comment by jorikfon** [comment]
Live CD сломал, доделываю уже.

**Comment by jorikfon** [comment]
Обновляется ок, но не монтирует диск после обновления, ковыряю дальше.

**Comment by jorikfon** [comment]
Установка из ISO ок,
Восстановление из ISO ок, 
Обновление через IMG ок.
