### ISSUE TITLE
Connecting a windows shared folder

### ISSUE THREAD

**Issue by boffart** [mikopbx/Core#531]
Расширить возможности управления дисками. 
Проанализировать возможность подключения общей папки для хранения записей разговоров и логов. 

`mount -t cifs //172.16.32.38/Scanner /mnt -o username=***,password=***,vers=2.0`

**Comment by jorikfon** [comment]
Можно в отдельный модуль, и там варианты S3, SMB, SFTP, FTP. Но не понятно что оно будет когда соединение пропадет, как будет Aster с удаленной папкой работать, разве что писать всегда на локальный storage, а потом перемещать, или делать симлинки. В саму бы АТС я такое не пихал от греха подальше :)

**Comment by jorikfon** [comment]
Вот для Яндекс облака хранить записи на s3 очень интересная задача, можно иметь неограниченное хранилище. Но это точно в отдельный модуль, и вот как раз не бекапов, в что нить типа внешнее хранилище для записей разговоров. Но надо чтобы и внешняя панель работала корректно и в случае разрыва записи не терялись. Может и правда делать симлинки в фоне, после переноса каждого файла наружу они ничего не занимают и логика никакая не сломается, будет разрыв, просто будут не доступны старые записи, а новые все лежат, как только монтирование диска возобновляется, файлы переносятся, а вместо них симлинки, или симлинки на папки...

Я бы для упрощения CORE бы из Storage класса убрал лишние функции монтирования, у нас там есть FTP и SFTP, я бы их в модуль бекапов бы и перенес. Чем меньше лишнего в базе, тем лучше. А уже в каждом модуле свои задачи и свой код для монтирования.

**Comment by boffart** [comment]
Пока оформил в виде статьи
https://wiki.mikopbx.ru/faq:shared-folder
согласен, лучше это в доп. модули выносить.
