### ISSUE TITLE
Remove the system integrity broken message and connect storage from LiveCD console menu

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#532]
Можно убрать надпись для LiveCD варианта, о том что файлы изменены? Или доделать чтобы оно правильно отрабатывало или скрыть эту надпись вообще. И еще под вопросом для чего там у нас пункт смонтировать Storage, это применимо как-то в LiveCD?

**Comment by jorikfon** [comment]
Кстати получается по умолчанию SSH отключен, на машину нельзя зайти при загрузке с LiveCD, а зачем тогда там Firewall, сбросить пароль?

Наверное можно в комплексе эту задачу завязать с задаче по проработке консольного меню под докер и облако и в зависимости от того в какой системе установлена АТС показывать разные варианты меню без лишних пунктов.

У нас в модели **PBXSettings** есть ключ **VirtualHardwareType**, можно в него при старте системы прописать тип окружения (t2sde, docker, t2sdeInYandex и т. д.) и потом отовсюду с ним работать и из веб интереса и из меню  консольного.

**Comment by jorikfon** [comment]
У меня так пишет 
Warning: Permanently added '172.16.32.156' (ECDSA) to the list of known hosts.
root@172.16.32.156: Permission denied (publickey).

Там по умолчанию же выключена авторизация по паролю?

**Comment by boffart** [comment]
https://github.com/mikopbx/Core/commit/2ebee548e54bb5c9d7645373880d13a0f57f5bb4

**Comment by boffart** [comment]
Готово
