### ISSUE TITLE
Do you want to support deploy by docker containers?

### ISSUE THREAD

**Issue by pahaz** [mikopbx/Core#566]
It's the easiest and reusable way. 

At the moment, I can't find any tools tools for self-assembly of the image. Is it an open process?

Docket is the best trusted way to use your software.

**Comment by boffart** [comment]
In releases, files with the tar extension are attached - this is the docker image. You can import it and use it. 
Or just follow the instructions https://docs.mikopbx.com/mikopbx/v/english/setup/docker
