### ISSUE TITLE
ERROR: Only linux 5 is supported... on Linux 6.1

### ISSUE THREAD

**Issue by lemon-sh** [mikopbx/Core#568]
The [documentation](https://docs.mikopbx.com/mikopbx/v/english/setup/docker) says:
> The "host system" must be running on **Linux 5+**.

So I figured that Linux 6.1 will work too, unfortunately, when I start the container, I get this error message:

```
lemon@pbx ~/miko [1]> doas docker container logs mikopbx
ERROR: Only linux 5 is supported...
ERROR: Only linux 5 is supported...
ERROR: Only linux 5 is supported...
ERROR: Only linux 5 is supported...
```

My system:
```
lemon@pbx ~/miko> uname -a
Linux pbx 6.1.38-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Wed, 05 Jul 2023 18:57:35 +0000 x86_64 Linux
lemon@pbx ~/miko> cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.0
PRETTY_NAME="Alpine Linux v3.18"
...
```

I am using the latest MikoPBX image from the GitHub packages.

**Comment by boffart** [comment]
all MikoPBX packages are built under the kernel version 5. I doubt they will run under the 6th kernel. take this not as a mistake, but as a limitation
