### ISSUE TITLE
Add AMI users command right 

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#612]
https://wiki.mikopbx.ru/asterisk-managers
У вас в wiki описан набор прав "Command", но на форме в WEB интерфейсе нет опции для выбора этих прав для пользователя 
![2023-09-06 19 49 18](https://github.com/mikopbx/Core/assets/5922918/2894d4fa-ec75-48c9-ad01-4c82787b1aaf)

**Comment by Abyss777** [comment]
Кстати после добавлении права `command` можно будет из коробки использовать стандартный шаблон Zabbix https://www.zabbix.com/ru/integrations/asterisk для мониторинга asterisk без `asterisk-stats.sh` отсюда https://wiki.mikopbx.ru/faq:zabbix

> You should enable the mini-HTTP Server, add the option webenabled=yes in the general section of the manager.conf file and create Asterisk Manager user with **system and command write permissions** within your Asterisk instance.

**Comment by boffart** [comment]
Поправил интерфейс. 
<img width="1155" alt="MikoPBX_Asterisk_Manager_Interface__AMI__—_Яндекс Браузер" src="https://github.com/mikopbx/Core/assets/5922739/896ada8d-1202-405b-9d5b-f816715a7d42">

то то не так с наиманием строки "public ?string  $command = '';" пока не написал имя свойства вручную - колонка в таблице не создавалась. Мб были какие то не видимые спецсимволы.
