### ISSUE TITLE
Add pagination on extensions index page

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#627]
При заполнении MikoPBX > 500 пользователями, сильно тормозит браузер на странице с сотрудниками, сделать получения сотрудников порциями, реализовать серверный поиск и сортировку.

**Comment by jorikfon** [comment]
Done

**Comment by ogt111** [comment]
Было бы здорово, если бы можно было указывать кастомно. Не только 10 позиций на странице.
