### ISSUE TITLE
Deprecated: crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#636]
Deprecated: crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format. in /offload/rootfs/usr/www/src/AdminCabinet/Controllers/SessionController.php on line 74 {"success":false,"reload":false,"message":{"error":["\u041e\u0448\u0438\u0431\u043a\u0430 \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u0438"]},"lastSentryEventId":null}

**Comment by boffart** [comment]
Вот тут обсуждение интересное
https://stackoverflow.com/questions/40201249/mcrypt-is-deprecated-how-to-crypt-and-save-a-password-correctly-in-php

**Comment by jorikfon** [comment]
Как бы это воспроизвести. Предполагаю что беда в устаревшем фальконе, но он же в своем окружении PHP 7.4, не понимаю пока что приводит к этой ошибке.
