### ISSUE TITLE
SIP Provider lost PROVIDER prefix in uuid

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#643]

**Comment by boffart** [comment]
Сейчас идентификатор провайдера описывается в виде 
```
SIP-1692280724
```

Тут специально укоротили ID, не все шлюзы поддерживают длинные значения. 

Идентификатор для учетки сотрудника в виде:
```
SIP-PHONE-EDEE3614
```
Тоже короткий. 

Мб не нужно ничего менять?

**Comment by jorikfon** [comment]
@boffart Я переделал для peer ID на HEX, потому что при массовом создании они дублировались.
Провайдеры тоже создаются с аналогичным укороченным ID теперь.
Т.е. сейчас это SIP-EDEE3614, можно сделать SIP-TRUNK-EDEE3614, та же длина получится, а конфиги если не знаком с нашими особенностями попроще читать и логи. 
Раньше было реально длинный SIP-PROVIDER-122642725b9265fd7151c
