### ISSUE TITLE
Remove zabbix_agentd from core

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#679]
Я пересобрал модуль Zabbix, бинарник агента положил внутрь модуля, можно убрать его из базового образа.

**Comment by boffart** [comment]
его убать из t2? или только из образа?

**Comment by jorikfon** [comment]
Можно вообще убрать. официальные дистрибутивы запускаются в MikoPBX, проверил 5 и 6 версию.

**Comment by jorikfon** [comment]
Хотя лучше где нить оставить кастомную команду для сборки, можно из образа вырезать, а в t2 оставить, под тот е АРМ если когда нить будем собирать...

**Comment by boffart** [comment]
Кастом команда  ` ./scripts/Build-Target -cfg 2024.0 -job 5-asterisk16`
Сборку zabbix отключил. Нужно в описании к релизу сообщить, что нужно ставить модуль, и не использовать инструкции с wiki.
