### ISSUE TITLE
Добавить возможность отключить защиту автоподъема на нескольких устройствах.

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#68]
Сейчас сломались несколько рабочих сценариев. Работа через встроенный софтфон, работа в режиме терминала во второй панели, из-за принудительной защиты автоподъема. Даже если мы используем специальный уникальный header он не доходит до SIP софтфона при мультирегистрации. 

Как можно сделать этот механизм более управляемым? Можем предусмотреть дополнительный параметр в Originate чтобы при указании его, защита выключалась и хидеры уходили на все устройства?

Например AllowMultiAnswer=Y

**Comment by boffart** [comment]
Зачем звонить средствами **Originate** когда есть встроенный софтфон? 
Это жуткий костыль. Может буть верно переработать архитектуру? 
Первая панель в режиме софтфона звонит без **Originate**.

**Comment by jorikfon** [comment]
Терминальный режим. Софтфон локально запущен и свернут, управление через панель в RDP сеансе, все с одного компьютера. Надо на локальном софтфоне поднять специальным хидером. 
Почему костыль то, все IP устройства автоподъём так делают. Нормальная схема. Для удобства подключен DECT, SIM карта, ни одна из них не сработает на автоподъём, сработает так как и должно быть. Сейчас это сломалось.

Ты решил виртуальную проблему и поломал текущие рабочие сценарии.

**Comment by boffart** [comment]
Готово

Теперь запрос звонка сводится к следующему:

```
Action: Originate
Channel: Local/201@internal-originate
Context: all_peers
Exten: 203
Priority: 1
Callerid: 201
Variable: SIPADDHEADER="Call-Info:\;answer-after=0",pt1c_cid=203,ALLOW_MULTY_ANSWER=1
```

- **ALLOW_MULTY_ANSWER** - не обязательный параметр
- кол-во необходимых параметров в Variable теперь стало меньше
- _IS_ORGNT=1,_extenfrom1c=1,_FROM_PEER=201 - теперь не обязательно указывать, они не используются.
