### ISSUE TITLE
Добавить в настройки ссылку на звуковой файл с оповещением о записи разговоров

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#69]
Я думаю в минимальном функционале надо такое реализовать, в некоторых странах незаконно использовать запись разговора без оповещения, а у нас нет такой возможности в принципе.
Я бы в общих настройках добавил возможность указать звуковой файл, если он указан то засунуть его во все диалпланы при соединении.
Вроде не самая большая задача, добавлю ее в список на будущие релизы.

_Originally posted by @jorikfon in https://github.com/mikopbx/Core/discussions/60#discussioncomment-362140_

**Comment by jorikfon** [comment]
В общих настройках системы добавил выбор аудиофайла, ссылка на ID сохраняется в переменной PBXRecordAnnouncement

Например будет фраза "Для обеспечения качества обслуживания, ваш разговор будет записан".
Далее, если файл выбран, он должен воспроизводиться перед соединением с первым человеком, если дальше его переадресуют, воспроизводить этот анонс не надо.

Анонс должен проигрываться 1 раз в разговоре, но всегда после всех других звуков (Приветствия, IVR, анонсы очереди, нерабочее время).

**Comment by jorikfon** [comment]
Ну это понятно, тут важно поймать момент когда соединяем на самого первого человека, и тогда проиграть анонс записи разговора. И больше не повторять его при переадресациях, переводах.

**Comment by jorikfon** [comment]
Реализовать отдельно сценарий для входящих и исходящих, соответственно переменные

- PBXRecordAnnouncementOut
- PBXRecordAnnouncementIn

**Comment by boffart** [comment]
готово
