### ISSUE TITLE
Issue with several months in one nonworking rule

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#698]
АТС позволяет ввести правило с несколькими месяцами. Например, правило для майских праздников 29.04.2024 - 05.05.2024.

same => n,GotoIfTime(*,*,29-5,apr-may?work-time-set-var-8,${EXTEN},1)

Такое правило также сработает с 01.04-05.04.2024

[2024-04-05 14:54:02] VERBOSE[29218][C-00000004] pbx.c: Executing [74951112233@check-out-work-time-8:4] GotoIfTime("PJSIP/SIP-1588858932-00000003", "*,*,29-5,apr-may?work-time-set-var-8,74951112233,1") in new stack
[2024-04-05 14:54:02] VERBOSE[29218][C-00000004] pbx_builtins.c: Goto (work-time-set-var-8,74951112233,1)

**Comment by boffart** [comment]
не совсем понял в чем ошибка? что нужно поправить? :)
да, можно указать несколько месяцев / несколько лет в одном правиле нерабочего времени.

**Comment by jorikfon** [comment]
Если я правильно понял пользователь хочет нерабочее время с 29 апреля по 5 мая.
А в результате получает несколько нерабочих периодов

- с 29 апреля по 30 апреля
- с 29 мая по 31 мая
- с 1 апреля по 5 апреля 
- с 1 мая по 5 мая

**Comment by jorikfon** [comment]
Хотя, надо все-таки проверить...

<img width="1004" alt="Screenshot 2024-04-08 at 12 11 36" src="https://github.com/mikopbx/Core/assets/5922918/c18e46e5-b8f0-4c38-ab18-734769ba69ea">

**Comment by ivstep** [comment]
В описании проблемы есть логи.
Настроено нерабочее правило 29.04.2024 -05.05.2024
Нерабочее время сработало 05.04.2024.

**Comment by boffart** [comment]
теперь понял, спасибо ) 
в новой АТС будет возможность подключить CalDav календари, там попроще будет праздники описывать.

**Comment by boffart** [comment]
Готово
