### ISSUE TITLE
Транслитерация Caller ID

### ISSUE THREAD

**Issue by alateas** [mikopbx/Core#7]
Многие современные телефоны и софтфоны поддерживают Caller ID состоящие в том числе из кириллических символов. Тестирование показало что пользователи вполне могут видеть имя звонящего на родном языке.
Насколько я понимаю настройки, позволяющей выключить транслитерацию Caller ID сотрудников нет.
В принципе это решается переопределением Caller ID в поле `Дополнительные параметры SIP учетки` для каждого сотрудника в отдельности таким образом:
```
[endpoint]
callerid = Пётр Иванов <150>
```
Но приходиться делать это вручную для каждого аккаунта.
Было бы здорово иметь возможность отключить транслитерацию на уровне системы.

**Comment by jorikfon** [comment]
@boffart  Мы же сделали это? Закрваем?

**Comment by boffart** [comment]
Да, сделано.
