### ISSUE TITLE
PV doesn't show upgrading status in serial console.

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#710]
<img width="571" alt="Screenshot 2024-04-26 at 14 44 49" src="https://github.com/mikopbx/Core/assets/5922918/58220c3b-1e1a-49a1-94d2-86e449adccff">
<img width="1003" alt="Screenshot 2024-04-26 at 14 45 00" src="https://github.com/mikopbx/Core/assets/5922918/c7450908-93b9-42b3-9eb8-6d9707fae120">

**Comment by jorikfon** [comment]
Еще в облаке очень долго обновляет из img, надо проверить на быстрой машине...

**Comment by boffart** [comment]
Я не представляю как это выводить в серийную консоль. Она работает инче, не так как обычная. Уже всяко пытался.

**Comment by boffart** [comment]
В облаке диски медленные нававерное медленные или количество операций дисковых ограничено. 
На ssd дисках локально все очень быстро отрабатывает.

**Comment by jorikfon** [comment]
Да, в VK прямо минут 10 идет обновление, в Google и AWS стандартно быстро. Может от дисков зависит, может от опций DD. Размер блока. Надо поэкспериментировать когда нибудь. 

Про консоль да, не понятно, пока записал как задачу на будущее...

**Comment by boffart** [comment]
Вот про dd кстати интересно. Всегда интересовало, почему на маке образ через dd записывается крайне долго. 
А вот на винде, через спец утилиты с GUI моментально. 
Наверное есть опции какие то.

**Comment by jorikfon** [comment]
Не трогай в этом релизе. 😅
Все проверил на всех возможных вариантах установок и облаках.
После релиза поковыряем.
