### ISSUE TITLE
Update gnats http port number in zephyr class

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#726]
If we use custom port, zephyr doesn't know about it

**Comment by talistech** [comment]
The same goes for:
- BEANSTALK_PORT
- REDIS_PORT
- GNATS_PORT

**Comment by jorikfon** [comment]
> * BEANSTALK_PORT
> * REDIS_PORT
> * GNATS_PORT

Can you share more details about the problem, where are you faced with it?

**Comment by talistech** [comment]
Related to #753, some custom ports defined in the docker-compose file are unused or not correctly assigned.
