### ISSUE TITLE
Check asterisk dropping calls after applying changes in custom files.

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#728]
Жалуются что при обновлении extension.conf рубит звонки, надо проверить и возможно расписать по существующим файлам более детально действия для каждого известного. Разобраться нужна ли такая избыточность перезапусксть протоколы, а потом core reload?

**Comment by jorikfon** [comment]
Даже при добавлении и сохранении сотрудника это происходит.

**Comment by boffart** [comment]
поправил

**Comment by belakovsergey** [comment]
Сделайте фикс, очень нужно

**Comment by boffart** [comment]
фикс тут
https://github.com/mikopbx/Core/commit/f7b96d61254ccc63e2b71dcb3188f6397851ba23
можно вручную файл поправить 
релиз пока не планируется.

**Comment by belakovsergey** [comment]
> фикс тут [f7b96d6](https://github.com/mikopbx/Core/commit/f7b96d61254ccc63e2b71dcb3188f6397851ba23) можно вручную файл поправить релиз пока не планируется. мб в течение месяца сделаем
Правка файла после перезагрузки атс, не сбросится ?

**Comment by pir0zhkov** [comment]
> фикс тут [f7b96d6](https://github.com/mikopbx/Core/commit/f7b96d61254ccc63e2b71dcb3188f6397851ba23) можно вручную файл поправить релиз пока не планируется. мб в течение месяца сделаем

Решили поправить вручную. Сломалось нерабочее время и наша интеграция с Регион-DXE. Звонки с региона не шли на мико, в обратную сторону работало. Вернули все обратно)

**Comment by boffart** [comment]
> > фикс тут [f7b96d6](https://github.com/mikopbx/Core/commit/f7b96d61254ccc63e2b71dcb3188f6397851ba23) можно вручную файл поправить релиз пока не планируется. мб в течение месяца сделаем
> 
> Решили поправить вручную. Сломалось нерабочее время и наша интеграция с Регион-DXE. Звонки с региона не шли на мико, в обратную сторону работало. Вернули все обратно)

Обязательно бекап. Я уже с 10 АТС установил с такой правкой, проверено, работает корректно. Мб что то упустили.
