### ISSUE TITLE
On the non working hours incoming rules set work like a puzzle

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#733]
https://github.com/mikopbx/Core/assets/5922918/e484bc47-398f-4b35-8c9b-dd5c9687fda7

**Comment by boffart** [comment]
это не ошибка - это нормальное поведение
судя во всему у вас используется один и тот же провайдер телефонии
логинятся учетные записи по одному и тому же IP адресу и порту
во входящем маршруте DID не указан, потому никоим образом не удастся отличить входящие вызовы через эти линии

уточните во вхдящих маршрутах DID номер (часто совпадает с логином)
и функционал нерабочего времени позволит это настроить как Вы хотите

**Comment by jorikfon** [comment]
Может форму надо другую, или DID вывести и сгруппировать по нему, а не по маршрутам? Очень выглядит странно.

**Comment by jorikfon** [comment]
Пользователь то ожидает, то что видит на форме, что он будет по маршрутам настраивать, а не по хостам, контекстам, did...

**Comment by jorikfon** [comment]
Таблицу, первая колонка выключатель, вторя дид, третья хост, четвертая список маршрутов в одной ячеке.
Можно 2и3 в одну ячеку сунуть

**Comment by boffart** [comment]
Там уже DID отображается. На твоем видео видно. 
Просто когда кликаешь "Звонок через любого провайдера" то этот случае затронет "все возможные did", потому и включаются остальные флажки

**Comment by jorikfon** [comment]
Там бы еще проверить откликивание. Потому что при выборе все переключатели двигаются, при снятии только один снимается.

**Comment by boffart** [comment]
Сейчас заложена следующая логика:

- Если отключаешь маршрут без указания DID - отключаются все маршруты без дид, маршруты с DID остаются включенными 
- Если отключаешь маршрут С указанным DID - отключаются все маршрутыбез дид и все маршруты с таким же DID
- Если включаешь маршрут без DID - то включаются все маршруты по этому провайдеру, тк "без дид" === "любой номер"
- Если включаешь маршрут с DID - включатся все маршруты с таким DID
