### ISSUE TITLE
Add information to the CDR through which provider the call was made

### ISSUE THREAD

**Issue by KingGrom** [mikopbx/Core#742]
Добавить информацию  в истории звонков ,через какого провайдера совершен звонок ,если провайдеров несколько

**Comment by boffart** [comment]
В ядро АТС этот функционал добавлять не планировали. 
Будет дополнительный модуль с расширенными функциями:
<img width="1145" alt="MikoPBX_Экспорт_записей_разговоров__группа_Вкладки_окна__—_Яндекс Браузер" src="https://github.com/mikopbx/Core/assets/5922739/63e26bf5-e4da-4f6a-bd5d-8b34b291a670">

**Comment by boffart** [comment]
Это платный модуль. Цену можете запросить на help@miko.ru
В макретплейс появится позже.
