### ISSUE TITLE
No storage disk after the first installation on virtual box

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#745]
При установке версии 2023.2.206, все как по инструкции, при установке последней версии 2024.1.114 после ребута диск не монтируется. Надо воспроизвести.

**Comment by boffart** [comment]
На образе mikopbx-2024.2.13-x86_64.iso все в порядке с этим. 
Проверь у себя, если все в порядке, то закрою задачу.

**Comment by boffart** [comment]
Проверил на сборке
mikopbx-2024.2.110-dev-x86_64.iso

согласно инструкции - фиксированные диски - все в порядке
пробовал динамические диски - также все корректно отработало
