### ISSUE TITLE
This job has attempted to execute more than 3 times without success in CallEvents (SQL error?)

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#754]
`Jun 19 16:10:03 daemon.warning php.backend[8581]:  1466716 from INBOX_6672d6bd2600f7.58044094 on MikoPBX\Core\System\BeanstalkClient::cleanTubes
Jun 19 16:17:06 daemon.crit php.backend[15051]:  This job has attempted to execute more than 3 times without success.
Jun 19 16:17:06 daemon.crit php.backend[15051]:  Job stats: {"id":"1467482","tube":"select_cdr_tube","state":"reserved","pri":"1024","age":"75","delay":"0","ttr":"2","time-left":"1","file":"0","reserves":"4","timeouts":"3","releases":"0","buries":"0","kicks":"0"}
Jun 19 16:17:06 daemon.crit php.backend[15051]:  Message: {"0":"{\"0\":\"id>:id: AND linkedid <> \\\"\\\"\",\"bind\":{\"id\":17551},\"group\":\"linkedid\",\"columns\":\"linkedid\",\"limit\":450,\"add_pack_query\":{\"0\":\"linkedid IN ({linkedid:array})\",\"bind\":{\"linkedid\":null},\"order\":\"start,id\"},\"miko_result_in_file\":true,\"order\":\"answer\"}","inbox_tube":"INBOX_6672da06825928.46174104"} on MikoPBX\Core\System\BeanstalkClient::wait
Jun 19 16:21:01 daemon.warning php.backend[17998]:  Delete outdated jobs1467530 from INBOX_6672da11263ef9.33672645`

**Comment by boffart** [comment]
Эта ошибки из за модуля ModuleExportRecords
Не могу понять причины возникноваения. Разбираюсь...

**Comment by boffart** [comment]
Модуль починил.
