### ISSUE TITLE
VitualBox if we use different controllers for disk systen doesn't start after installation

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#758]
Воспроизводится в VitualBox, может быть и в реальной системе. Если загрузочный диск на IDE, а диск хранения на SCSI контроллере, то после устнаовки система корректно не стартует. Надо проверить.

**Comment by boffart** [comment]
Проверил на сборке mikopbx-2024.2.10-x86_64
Все в порядке. 

Системный диск на IDE 
Диск для хранения данных на SCSI

Разве это не та же задача, что закрыта ранее была? Про подключение storage при установке и про дефолтный конфиг? 

Текущий релиз с этим плохо работает, там ребут дополнительный нужен с ручным подключением диска через консольное меню.

**Comment by jorikfon** [comment]
Проблема была на IDE+SATA

**Comment by boffart** [comment]
Проверил вот с такой конфигурацией: 
<img width="813" alt="Снимок экрана 2024-07-30 в 14 29 58" src="https://github.com/user-attachments/assets/3750c284-cef7-4309-bb3f-2b626b3e945d">
Загрузочный диск был на SATA контроллере. 

После ребута система не загрузилась, в информации по диску **Actual size** был равен 2Мб. 
После повторного ребута **Actual size** изменился на адекватный. 

Я не вижу тут бага MikoPBX - вероятно Virtual Box как то по своему работает с динамическими дисками.

**Comment by boffart** [comment]
Я проверял на образе mikopbx-2024.2.13-x86_64.iso.

**Comment by boffart** [comment]
Выполнил тесты на образе mikopbx-2024.2.110-dev-x86_64.iso 
Проблема более не воспроизводится. Version 7.0.18 r162988 (Qt5.15.2)
