### ISSUE TITLE
CallerID(name) in notifications

### ISSUE THREAD

**Issue by MrLyu49** [mikopbx/Core#764]
В описании шаблона email-уведомления ГП может использоваться переменная VM_CALLERID, которая объединяет имя и номер звонящего. Но если в Invite имени нет, то оказывается, АТС принудительно его не устанавливает! Однако, если номер есть в Телефонной книге, то Модуль Телефонная книга подставляет этот параметр принудительно, игнорируя данные из Invite.

Замечательно, но если модуль это делает, то уж в базовой функциональности АТС само собой хотелось бы иметь такую принудительную подстановку. Ведь по сути список сотрудников с их мобильными и внутренними телефонами - тоже своего рода телефонная книга. И уведомления ГП могли бы быть существенно более информативными. Сотрудник по полученному уведомлению сразу бы увидел, кто из сотрудников ему оставил сообщение, и вероятно, мог бы решить, слушать ли сообщение сразу или отложить, а может, перезвонить. И это касается не только внешних (мобильных), но и внутренних номеров.

Кстати, в Истории вызовов номера сопровождаются именами из Списка сотрудников (т.е. в принципе базовая АТС это умеет делать), но в генерируемых уведомлениях ГП - нет?

А в уведомлении о пропущенном вызове имени нет, даже если номер присутствует в Телефонной книге!? Тоже хотелось бы подставлять имя звонившего как из Телефонной книги, так и из Списка сотрудников.

И если делать эту доработку, то прошу учесть еще пожелание о приоритетности имени из Телефонной книги перед именем из Списка сотрудников, если номер есть в обоих.

**Comment by MrLyu49** [comment]
Алексей, новый параметр для оповещений о пропущенных - это отлично! Я так понимаю, теперь ждем очередной релиз?

Но поясните, этот параметр сможет подставлять имя принудительно только из телефонной книги, как она было ранее сделано в сообщениях ГП? А что насчет принудительной подстановки из списка сотрудников, о чем я писал в первой части моего текста?

**Comment by boffart** [comment]
Этот параметр работает **только** по списку сотрудников.  Для пропущенных всегда будет выполнять сопоставление по списку. 
Для голосовой почты только в том случае, если в VM_CALLERID нет name.

**Comment by MrLyu49** [comment]
Алексей, я обратил внимание, что новый параметр NOTIFICATION_NAME_TO - это не то, о чем я писал изначально. Подставлять имя адресата звонка тоже интересно, но речь-то шла о подстановке имени звонящего, хотя бы по списку сотрудников, чтобы в оповещении было сразу видно, кто из сотрудников звонил (если это был сотрудник с внутреннего или своего мобильного). Т.е. нужно дозаполнить параметр NOTIFICATION_CALLERID или заполнить новый параметр NOTIFICATION_CALLER_NAME.

Кстати, Вы сделали заполнение VM_CALLER_NAME по списку сотрудников как по внутреннему, так и по мобильному номеру звонящего?
