### ISSUE TITLE
При включенном редиректе на https не работает прослушивание/скачивание записи из 1С

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#77]
https://github.com/mikopbx/Core/blob/03e43330e72c2e4dc107883d4f2ef06d306a3566/src/Core/System/Configs/NginxConf.php#L109

В конфиге http-server.conf при обращении с 127.0.0.1 необходимо оставить инклуд

include mikopbx/locations/*.conf

**Comment by boffart** [comment]
Готово, будет доступно в следующем релизе.
