### ISSUE TITLE
IAX2 trunk, configuration issues

### ISSUE THREAD

**Issue by sgvoxlink** [mikopbx/Core#782]
Штатный функционал транка не работает:
в ответ на настройки, указанные в веб-интерфейсе, (например, host=pbx.abc.ru), в конфиге создается запись host=dynamic
а параметр username в конфиг уходит вообще закомментированным.

Из-за этого функционал транка становится нерабочим и решается только если сделать override этого конфига, вручную вписав нормальные параметры.
Ну и добавление параметра auth=md5 тоже не совсем ясно какую преследует цель, потому что это может лишь ломать поведение системы: ведь далее следует пароль в обычном открытом виде, а не его хэш.

[IAX-TRUNK-0BAC987D];

auth=md5
host=dynamic
;username=IAX-TRUNK-0BAC987D

![miko1](https://github.com/user-attachments/assets/312a0f66-1309-4a84-b176-78f4e2f4bf89)
![miko2](https://github.com/user-attachments/assets/ed846d3f-ba99-4f0c-bcd3-f896b1292aeb)

**Comment by boffart** [comment]
В доп. параметрах теперь будет вомзожность прописать настройки вручную:
```
disallow = all
username = IAX-TRUNK-DC0B7FF5
trunk = yes
secret = ckmkapV89
host = dynamic
```

в поле "хост" появится возможность через : указать порт

```
host = dynamic
```
по умолчанию будет именно так, но есть возможность переопределить эту опцию через доп. параметры
иначе оно как то странно работает при указании доменного имени

`auth=md5` - заменил на `plaintext`
