### ISSUE TITLE
CallerID format in PJSIP.conf

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#796]
При создании учетной записи PJSIP в системе CallerID устанавливается в формате Имя <добавочный номер>, например, Test <200>. Однако, при отправке уведомлений по электронной почте отображается только добавочный номер (200) без имени пользователя.

Я временно решил эту проблему вручную, заменив 200 на Test в конфигурационных файлах, и уведомления стали отображаться корректно. Однако данный подход работает только для небольшого количества пользователей (например, 15 человек). При увеличении числа пользователей до 100 или 200, постоянное редактирование конфигурационных файлов становится крайне неудобным и неэффективным.

**Шаги для воспроизведения:**

	1.	Создать новую учетную запись PJSIP в MikoPBX.
	2.	Проверить что CallerID в формате Имя <добавочный номер>, например, Test <200>.
	3.	Сгенерировать уведомление по электронной почте.
	4.	Обратить внимание, что в уведомлении отображается только добавочный номер (200) без имени пользователя.

**Ожидаемое поведение:**

Уведомления по электронной почте должны содержать полный CallerID, включая как имя пользователя, так и добавочный номер, например, Test <200>.

**Фактическое поведение:**

В уведомлениях отображается только добавочный номер (200) без имени пользователя.

**Comment by boffart** [comment]
вот тут. было сделано
https://github.com/mikopbx/Core/issues/764
