### ISSUE TITLE
Can't delete default MoH audio files

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#800]
MikoPBX 2024.1.114

Удаляю стандартные файлы, загружаю свой, возвращаюсь в список - стандартные файлы вернулись.

![mikopbx_moh](https://github.com/user-attachments/assets/4d4d0d7f-e7c3-457f-afba-84ff56af27cf)

**Comment by boffart** [comment]
Это фича, а не баг. Идея в том, что не должен быть этот список пустым. 
Если список файлов пуст, то они подтянутся дефолтные
В тоем случае нужно либо заменить существующий файл на твой, либо добавить новый, а затем удалить дефолтные

недавно ставил клиенту, там именно заменил файл на новый

**Comment by ivstep** [comment]
Непонятно реализовано. Можно добавить запрет удаления последнего файла, показывать поясняющее сообщение.
