### ISSUE TITLE
CA certs issue

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#804]
Опять начало ругаться на валидные сертификаты, надо проверить механизм обновления CA сертификатов, или может быть на станцию добавить воркер?
Тест 
```bash
curl --cert-status https://lic.miko.ru/protect/v1/ping -v
```

**Comment by boffart** [comment]
`curl https://lic.mikopbx.com/protect/v1/ping`
это работет
`curl https://lic.miko.ru/protect/v1/ping`
это нет

**Comment by boffart** [comment]
Исправил в сборке t2
