### ISSUE TITLE
iax.conf is not filled out when adding extensions

### ISSUE THREAD

**Issue by John-D-Doe** [mikopbx/Core#822]
In order to connect with IAX to MikoPBX it would be necessary that also iax.conf would be managed when extensions are manipulated via the MikoPBX webGUI - and that a firewall option for enabling/disabling IAX would be added. Strangely, when I set up the MikoPBX a month ago, there was the firewall entry for IAX - but now on two fresh installations, it does not appear anymore.

For each extension, the following entries are needed in iax.conf (203 is an example for extension 203)

[203] 
username = 203
password = <same as in pjsip.conf for same extension>
type=friend
host=dynamic
context = all_peers

**Comment by boffart** [comment]
see
https://github.com/mikopbx/Core/issues/782
We fixed a number of problems with a related task. I checked on the current dev version, in the firewall settings it is possible to configure access to the IAX port
