### ISSUE TITLE
Unable to choose audio file in default incoming route

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#835]
2024.2.28-dev

В настройках входящих маршрутов звонков в маршруте по умолчанию при действии "Воспроизвести медиа файл" при выборе аудио файла сначала появляется окно регистрации ошибки sentry, поле выбора файла пустое.

**Comment by boffart** [comment]
Это dev сброрка, pre релиз, в ней куча проблем. 
Вот более новая сборка, на ней проверь, все норм вроде:
https://files.miko.ru/s/TEBUPGNERWWQWpx

**Comment by boffart** [comment]
Наша рабочая АТС 2024.2.28-dev, на ней проблема тоже не воспроизводится

**Comment by ivstep** [comment]
2024.2.100 - воспроизводится.
Выполнил установку с нуля. Перехожу во входящие маршруты, маршрут по умолчанию - "Воспроизвести медиа файл", поле с выбором файла пустое

**Comment by boffart** [comment]
Воспроизвелось, достаточно почистить кэш браузера и ошибка появляется
