### ISSUE TITLE
Добавить службу для кеширования Redis server и расширение PHP-REDIS

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#84]
Служба Redis server

https://redislabs.com/get-started-with-redis/

PHP-REDIS
https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown

И добавить расширение в автозагрузку на подобии Phalcon, а службу в автостарт. 
А я провайдеры кеша перепишу на него, в лицензировании уже делал, потому должно быстро получиться.

**Comment by boffart** [comment]
Сделано. Уже в репозитории.
