### ISSUE TITLE
2 значные внутренние номера

### ISSUE THREAD

**Issue by plastilincheg** [mikopbx/Core#9]
Здравствуйте. Возможно добавить двузначные номера для использования? Для небольших офисов до 5 человек либо миграции с УАТС - достаточно важно.

**Comment by jorikfon** [comment]
@boffart не помнишь почему мы в мико ушли от них? Мне кажется была проблема с вызовом скорой и пожарной, технических проблем не было вроде...

**Comment by plastilincheg** [comment]
В Украине все экстренные службы трёхзначные

**Comment by jorikfon** [comment]
Сделаем!
ASK-817 Разрешить двузначные номера для внутренних

**Comment by 112358aalexx** [comment]
Если закрыть в коде использование 0Х вариантов для внутренних пиров, то вполне оправданное снятие ограничений

**Comment by jorikfon** [comment]
Сделано. В релизе.
