### ISSUE TITLE
Постоянно перезапускается rsyslog

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#95]
Логи забиты строчками
May 26 20:35:59 user.notice rsyslogd:  rsyslogd ended with exit status 1
May 26 20:35:59 user.notice rsyslogd:  rsyslogd died with code 1.
May 26 20:35:59 user.notice rsyslogd:  Automatically restarting rsyslogd.

Повторяется и на рабочей и на тестовых

**Comment by boffart** [comment]
Поправил
