### ISSUE TITLE
В МИКО настроил для исходящих вызовов оповещение о записи, оно не произносится

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#96]
Может модуль SmartIVR влияет? Как сделать чтобы не влиял?

**Comment by boffart** [comment]
Модуль SmartIVR влияет только на входящие, это AGI скрипт по сути. 
На исходящие не влияет совсем.

**Comment by boffart** [comment]
Проверил, проблем не обнаружил. Работает.
