### ISSUE TITLE
High Availability / Redundancy

### ISSUE THREAD

**Issue by thomasklosinsky** [mikopbx/Core#99]
Hi,
is there any HA or redundancy feature/module available or planned?

And any possibility to install mikopbx on Ubuntu?

**Comment by boffart** [comment]
Hi
There is no such possibility yet. 
It is possible to back up data via sftp. 
We plan to install mikopbx on debian, but this is not a priority.

Sample demo installation script for v.**2020.1.124**:
https://files.miko.ru/s/p6BM3FoajO7XV66/download
